import ISO6391 from "iso-639-1";
import chinaAreaData from "china-area-data";
// 格式化省市区数据为 el-cascader 可用结构
export function formatChinaArea() {
  const provs = chinaAreaData["86"];
  const arr = [];

  for (const provCode in provs) {
    const provName = provs[provCode];
    const cityData = chinaAreaData[provCode];

    const cities = [];
    for (const cityCode in cityData) {
      const cityName = cityData[cityCode];
      const districtData = chinaAreaData[cityCode] || {};

      const districts = Object.entries(districtData).map(([code, name]) => ({
        label: name,
        // value: code,
        value: name,
      }));

      cities.push({
        label: cityName,
        // value: cityCode,
        value: cityName,
        children: districts,
      });
    }

    // arr.push({ label: provName, value: provCode, children: cities });
    arr.push({ label: provName, value: provName, children: cities });
  }

  return arr;
}
export function getLanguageList() {
  const codes = ISO6391.getAllCodes();

  return codes.map((code) => {
    const nativeName = ISO6391.getNativeName(code); // 母语（如 English、日本語）
    // const chineseName = getChineseName(code, nativeName); // 中文

    return {
      code: nativeName,
      //   name: `${chineseName} (${nativeName})`, // 你要的格式：中文(母语)
      name: nativeName,
    };
  });
}
// 内置所有语言的中文名称（最全、最标准）
function getChineseName(code, nativeName) {
  const map = {
    zh: "中文",
    en: "英语",
    ja: "日语",
    ko: "韩语",
    fr: "法语",
    de: "德语",
    es: "西班牙语",
    pt: "葡萄牙语",
    ru: "俄语",
    it: "意大利语",
    ar: "阿拉伯语",
    hi: "印地语",
    id: "印尼语",
    ms: "马来语",
    th: "泰语",
    vi: "越南语",
    tr: "土耳其语",
    nl: "荷兰语",
    el: "希腊语",
    hu: "匈牙利语",
    pl: "波兰语",
    cs: "捷克语",
    sv: "瑞典语",
    fi: "芬兰语",
    da: "丹麦语",
    no: "挪威语",
    he: "希伯来语",
    fa: "波斯语",
    uk: "乌克兰语",
    ro: "罗马尼亚语",
    bg: "保加利亚语",
    hr: "克罗地亚语",
    sk: "斯洛伐克语",
    sl: "斯洛文尼亚语",
    lt: "立陶宛语",
    lv: "拉脱维亚语",
    et: "爱沙尼亚语",
    fil: "菲律宾语",
    bn: "孟加拉语",
    ur: "乌尔都语",
    mk: "马其顿语",
    mg: "马尔加什语",
    mt: "马耳他语",
    mi: "毛利语",
    mr: "马拉地语",
    mn: "蒙古语",
    ne: "尼泊尔语",
    oc: "奥克语",
    or: "奥里亚语",
    om: "奥罗莫语",
    os: "奥塞梯语",
    pi: "巴利语",
    ps: "普什图语",
    pa: "旁遮普语",
    qu: "克丘亚语",
    rm: "罗曼什语",
    rn: "隆迪语",
    se: "萨米语",
    sm: "萨摩亚语",
    sg: "桑戈语",
    sa: "梵语",
    sc: "撒丁语",
    sn: "绍纳语",
    sd: "信德语",
    si: "僧伽罗语",
    so: "索马里语",
    st: "塞索托语",
    su: "巽他语",
    sw: "斯瓦希里语",
    ta: "泰米尔语",
    te: "泰卢固语",
    tg: "塔吉克语",
    ti: "提格雷语",
    bo: "藏语",
    tk: "土库曼语",
    tl: "他加禄语",
    tn: "茨瓦纳语",
    to: "汤加语",
    ts: "聪加语",
    tt: "鞑靼语",
    tw: "特威语",
    ug: "维吾尔语",
    uz: "乌兹别克语",
    ve: "文达语",
    wa: "瓦隆语",
    cy: "威尔士语",
    wo: "沃洛夫语",
    xh: "科萨语",
    yi: "意第绪语",
    yo: "约鲁巴语",
    za: "壮语",
    zu: "祖鲁语",
  };
  return map[code] || nativeName;
}
export const languages = [
  { value: 17, cn: "阿布哈西亚文", en: "Abkhazian" },
  { value: 157, cn: "亚齐文", en: "Achinese" },
  { value: 158, cn: "阿乔利文", en: "Acoli" },
  { value: 159, cn: "阿当梅文", en: "Adangme" },
  { value: 160, cn: "阿迪何文", en: "Adyghe" },
  { value: 156, cn: "阿法文", en: "Afar" },
  { value: 19, cn: "南非荷兰文", en: "Afrikaans" },
  { value: 161, cn: "Afro-Asiatic 语", en: "Afro-Asiatic languages" },
  { value: 163, cn: "阿伊努文", en: "Ainu" },
  { value: 164, cn: "阿肯文", en: "Akan" },
  { value: 500, cn: "Alacalufan 语", en: "Alacalufan languages" },
  { value: 20, cn: "阿尔巴尼亚文", en: "Albanian" },
  { value: 534, cn: "Albanian 语", en: "Albanian languages" },
  { value: 166, cn: "阿留申文", en: "Aleut" },
  { value: 501, cn: "Algic 语", en: "Algic languages" },
  { value: 167, cn: "Algonquian 语", en: "Algonquian languages" },
  { value: 469, cn: "Altaic 语", en: "Altaic languages" },
  { value: 21, cn: "阿姆哈拉文", en: "Amharic" },
  { value: 170, cn: "昂加文", en: "Angika" },
  { value: 171, cn: "Apache 语", en: "Apache languages" },
  { value: 6, cn: "阿拉伯文", en: "Arabic" },
  { value: 173, cn: "阿拉贡文", en: "Aragonese" },
  { value: 175, cn: "阿拉帕霍文", en: "Arapaho" },
  { value: 502, cn: "Arauan 语", en: "Arauan languages" },
  { value: 177, cn: "阿拉瓦克文", en: "Arawak" },
  { value: 503, cn: "Arawakan 语", en: "Arawakan languages" },
  { value: 22, cn: "亚美尼亚文", en: "Armenian" },
  { value: 176, cn: "人工语言", en: "Artificial languages" },
  { value: 127, cn: "Asante 语", en: "Asante" },
  { value: 23, cn: "阿萨姆文", en: "Assamese" },
  { value: 547, cn: "亞述语", en: "Assyrian" },
  { value: 178, cn: "阿斯图里亚思特文", en: "Asturian" },
  { value: 179, cn: "Athapascan 语", en: "Athapascan languages" },
  { value: 180, cn: "Australian 语", en: "Australian languages" },
  { value: 499, cn: "Austro-Asiatic 语", en: "Austro-Asiatic languages" },
  { value: 346, cn: "Austronesian 语", en: "Austronesian languages" },
  { value: 181, cn: "阿瓦尔文", en: "Avaric" },
  { value: 183, cn: "阿瓦乔文", en: "Awadhi" },
  { value: 24, cn: "艾马拉文", en: "Aymara" },
  { value: 25, cn: "阿塞拜疆文", en: "Azerbaijani" },
  { value: 187, cn: "巴里文", en: "Balinese" },
  { value: 189, cn: "Baltic 语", en: "Baltic languages" },
  { value: 28, cn: "俾路支文", en: "Baluchi" },
  { value: 186, cn: "班巴拉文", en: "Bambara" },
  { value: 185, cn: "Bamileke 语", en: "Bamileke languages" },
  { value: 184, cn: "Banda 语", en: "Banda languages" },
  { value: 123, cn: "Bantu 语", en: "Bantu languages" },
  { value: 188, cn: "巴萨文", en: "Basa" },
  { value: 26, cn: "巴什客尔文", en: "Bashkir" },
  { value: 27, cn: "巴斯克文", en: "Basque" },
  { value: 198, cn: "Batak 语", en: "Batak languages" },
  { value: 190, cn: "别札文", en: "Beja" },
  { value: 34, cn: "白俄罗斯文", en: "Belarusian" },
  { value: 191, cn: "别姆巴文", en: "Bemba" },
  { value: 8, cn: "孟加拉文", en: "Bengali" },
  { value: 192, cn: "Berber 语", en: "Berber languages" },
  { value: 193, cn: "博杰普尔文", en: "Bhojpuri" },
  { value: 29, cn: "Bihari 语", en: "Bihari languages" },
  { value: 194, cn: "毕库尔文", en: "Bikol" },
  { value: 201, cn: "布林文", en: "Bilin" },
  { value: 195, cn: "比尼文", en: "Bini" },
  { value: 30, cn: "比斯拉马文", en: "Bislama" },
  { value: 140, cn: "波斯尼亚文", en: "Bosnian" },
  { value: 197, cn: "布拉杰文", en: "Braj" },
  { value: 31, cn: "布里多尼文", en: "Breton" },
  { value: 200, cn: "布吉文", en: "Buginese" },
  { value: 32, cn: "保加利亚文", en: "Bulgarian" },
  { value: 199, cn: "布里亚特文", en: "Buriat" },
  { value: 33, cn: "缅甸文", en: "Burmese" },
  { value: 202, cn: "卡多文", en: "Caddo" },
  { value: 509, cn: "Caddoan 语", en: "Caddoan languages" },
  { value: 141, cn: "粤语", en: "Cantonese" },
  { value: 36, cn: "加泰罗尼亚文", en: "Catalan" },
  { value: 205, cn: "Caucasian 语", en: "Caucasian languages" },
  { value: 152, cn: "宿务文", en: "Cebuano" },
  { value: 206, cn: "Celtic 语", en: "Celtic languages" },
  {
    value: 203,
    cn: "Central American Indian 语",
    en: "Central American Indian languages",
  },
  {
    value: 526,
    cn: "Central Malayo-Polynesian 语",
    en: "Central Malayo-Polynesian languages",
  },
  { value: 508, cn: "Chadic 语", en: "Chadic languages" },
  { value: 220, cn: "Chamic 语", en: "Chamic languages" },
  { value: 207, cn: "查莫罗文", en: "Chamorro" },
  { value: 209, cn: "车臣文", en: "Chechen" },
  { value: 216, cn: "彻罗基文", en: "Cherokee" },
  { value: 219, cn: "夏延文", en: "Cheyenne" },
  { value: 505, cn: "Chibchan 语", en: "Chibchan languages" },
  { value: 2, cn: "中文", en: "Chinese" },
  { value: 213, cn: "契努克文", en: "Chinook jargon" },
  { value: 215, cn: "佩瓦扬文", en: "Chipewyan" },
  { value: 214, cn: "乔克托文", en: "Choctaw" },
  { value: 211, cn: "楚吾克文", en: "Chuukese" },
  { value: 218, cn: "楚瓦什文", en: "Chuvash" },
  { value: 222, cn: "凯尔特文", en: "Cornish" },
  { value: 37, cn: "科西嘉文", en: "Corsican" },
  { value: 225, cn: "克里族文", en: "Cree" },
  { value: 363, cn: "克里克文", en: "Creek" },
  { value: 227, cn: "Creoles and pidgins 语", en: "Creoles and pidgins" },
  { value: 226, cn: "克里米亚土耳其文", en: "Crimean Tatar" },
  { value: 38, cn: "克罗地亚文", en: "Croatian" },
  { value: 229, cn: "Cushitic 语", en: "Cushitic languages" },
  { value: 39, cn: "捷克文", en: "Czech" },
  { value: 230, cn: "达科他文", en: "Dakota" },
  { value: 40, cn: "丹麦文", en: "Danish" },
  { value: 231, cn: "达尔格瓦文", en: "Dargwa" },
  { value: 233, cn: "特拉华文", en: "Delaware" },
  { value: 147, cn: "迪维西语", en: "Dhivehi" },
  { value: 236, cn: "丁卡文", en: "Dinka" },
  { value: 237, cn: "多格拉文", en: "Dogri" },
  { value: 235, cn: "多格里布文", en: "Dogrib" },
  { value: 238, cn: "Dravidian 语", en: "Dravidian languages" },
  { value: 240, cn: "都阿拉文", en: "Duala" },
  { value: 41, cn: "荷兰文", en: "Dutch" },
  { value: 242, cn: "迪尤拉文", en: "Dyula" },
  { value: 243, cn: "不丹文", en: "Dzongkha" },
  { value: 512, cn: "East Germanic 语", en: "East Germanic languages" },
  { value: 542, cn: "East Slavic 语", en: "East Slavic languages" },
  { value: 258, cn: "东弗里西亚文", en: "Eastern Frisian" },
  {
    value: 528,
    cn: "Eastern Malayo-Polynesian 语",
    en: "Eastern Malayo-Polynesian languages",
  },
  { value: 533, cn: "Eastern Sudanic 语", en: "Eastern Sudanic languages" },
  { value: 148, cn: "埃菲克文", en: "Efik" },
  { value: 245, cn: "埃克丘克文", en: "Ekajuk" },
  { value: 1, cn: "英文", en: "English" },
  {
    value: 146,
    cn: "English-Based Creoles and pidgins 语",
    en: "English-Based Creoles and pidgins",
  },
  { value: 367, cn: "俄日亚文", en: "Erzya" },
  { value: 510, cn: "Eskimo-Aleut 语", en: "Eskimo-Aleut languages" },
  { value: 42, cn: "世界文", en: "Esperanto" },
  { value: 43, cn: "爱沙尼亚文", en: "Estonian" },
  { value: 248, cn: "埃维文", en: "Ewe" },
  { value: 249, cn: "旺杜文", en: "Ewondo" },
  { value: 250, cn: "芳格文", en: "Fang" },
  { value: 251, cn: "芳蒂文", en: "Fanti" },
  { value: 44, cn: "法罗文", en: "Faroese" },
  { value: 45, cn: "斐济文", en: "Fijian" },
  { value: 252, cn: "菲律宾文", en: "Filipino" },
  { value: 46, cn: "芬兰文", en: "Finnish" },
  { value: 253, cn: "Finno-Ugrian 语", en: "Finno-Ugrian languages" },
  { value: 139, cn: "佛兰芒文", en: "Flemish" },
  { value: 254, cn: "丰文", en: "Fon" },
  { value: 511, cn: "Formosan 语", en: "Formosan languages" },
  { value: 9, cn: "法文", en: "French" },
  {
    value: 223,
    cn: "French-Based Creoles and pidgins 语",
    en: "French-Based Creoles and pidgins",
  },
  { value: 260, cn: "弗留利文", en: "Friulian" },
  { value: 259, cn: "夫拉文", en: "Fulah" },
  { value: 261, cn: "加文", en: "Ga" },
  { value: 204, cn: "巴勒比文", en: "Galibi Carib" },
  { value: 49, cn: "加利西亚文", en: "Galician" },
  { value: 336, cn: "卢干达文", en: "Ganda" },
  { value: 262, cn: "迦约文", en: "Gayo" },
  { value: 263, cn: "葛巴亚文", en: "Gbaya" },
  { value: 50, cn: "格鲁吉亚文", en: "Georgian" },
  { value: 12, cn: "德文", en: "German" },
  { value: 264, cn: "Germanic 语", en: "Germanic languages" },
  { value: 266, cn: "吉尔伯特斯文", en: "Gilbertese" },
  { value: 270, cn: "岗德文", en: "Gondi" },
  { value: 271, cn: "科洛涅达罗文", en: "Gorontalo" },
  { value: 273, cn: "格列博文", en: "Grebo" },
  { value: 51, cn: "希腊文", en: "Greek" },
  { value: 515, cn: "希臘语", en: "Greek languages" },
  { value: 53, cn: "瓜拉尼文", en: "Guarani" },
  { value: 54, cn: "古吉拉特文", en: "Gujarati" },
  { value: 276, cn: "吉维克琴文", en: "Gwich'in" },
  { value: 277, cn: "海达文", en: "Haida" },
  { value: 278, cn: "海地文", en: "Haitian" },
  { value: 55, cn: "豪萨文", en: "Hausa" },
  { value: 279, cn: "夏威夷文", en: "Hawaiian" },
  { value: 56, cn: "希伯来文", en: "Hebrew" },
  { value: 280, cn: "赫雷罗文", en: "Herero" },
  { value: 281, cn: "希利盖农文", en: "Hiligaynon" },
  { value: 282, cn: "Himachali 语", en: "Himachali languages" },
  { value: 4, cn: "印地文", en: "Hindi" },
  { value: 284, cn: "希里莫图文", en: "Hiri Motu" },
  { value: 145, cn: "赫蒙文", en: "Hmong" },
  { value: 516, cn: "Hmong-Mien 语", en: "Hmong-Mien languages" },
  { value: 517, cn: "Hokan 语", en: "Hokan languages" },
  { value: 57, cn: "匈牙利文", en: "Hungarian" },
  { value: 286, cn: "胡帕文", en: "Hupa" },
  { value: 287, cn: "伊班文", en: "Iban" },
  { value: 58, cn: "冰岛文", en: "Icelandic" },
  { value: 288, cn: "伊布文", en: "Igbo" },
  { value: 291, cn: "Ijo 语", en: "Ijo languages" },
  { value: 293, cn: "伊洛干诺文", en: "Iloko" },
  { value: 438, cn: "伊纳里萨米文", en: "Inari Sami" },
  { value: 294, cn: "Indic 语", en: "Indic languages" },
  { value: 295, cn: "Indo-European 语", en: "Indo-European languages" },
  { value: 518, cn: "Indo-Iranian 语", en: "Indo-Iranian languages" },
  { value: 11, cn: "印度尼西亚文", en: "Indonesian" },
  { value: 296, cn: "印古什文", en: "Ingush" },
  { value: 59, cn: "国际文字", en: "Interlingua" },
  { value: 60, cn: "国际文字（E）", en: "Interlingue" },
  { value: 292, cn: "因纽特文", en: "Inuktitut" },
  { value: 61, cn: "依奴皮维克文", en: "Inupiaq" },
  { value: 297, cn: "Iranian 语", en: "Iranian languages" },
  { value: 62, cn: "爱尔兰文", en: "Irish" },
  { value: 298, cn: "Iroquoian 语", en: "Iroquoian languages" },
  { value: 63, cn: "意大利文", en: "Italian" },
  { value: 519, cn: "Italic 语", en: "Italic languages" },
  { value: 13, cn: "日文", en: "Japanese" },
  { value: 64, cn: "爪哇文", en: "Javanese" },
  { value: 546, cn: "Jola-Fonyi 语", en: "Jola-Fonyi languages" },
  { value: 545, cn: "Jola-Kasa 语", en: "Jola-Kasa languages" },
  { value: 301, cn: "犹太阿拉伯文", en: "Judeo-Arabic" },
  { value: 300, cn: "犹太波斯文", en: "Judeo-Persian" },
  { value: 309, cn: "卡巴尔达文", en: "Kabardian" },
  { value: 303, cn: "卡比尔文", en: "Kabyle" },
  { value: 304, cn: "卡琴文", en: "Kachin" },
  { value: 52, cn: "格陵兰文", en: "Kalaallisut" },
  { value: 486, cn: "卡尔梅克文", en: "Kalmyk" },
  { value: 305, cn: "卡姆巴文", en: "Kamba" },
  { value: 65, cn: "卡纳达文", en: "Kannada" },
  { value: 307, cn: "卡努里文", en: "Kanuri" },
  { value: 302, cn: "卡拉卡尔帕克文", en: "Kara-Kalpak" },
  { value: 319, cn: "卡拉恰伊巴尔卡尔文", en: "Karachay-Balkar" },
  { value: 320, cn: "卡累利阿文", en: "Karelian" },
  { value: 306, cn: "Karen 语", en: "Karen languages" },
  { value: 66, cn: "克什米尔文", en: "Kashmiri" },
  { value: 228, cn: "卡舒文", en: "Kashubian" },
  { value: 67, cn: "哈萨克文", en: "Kazakh" },
  { value: 310, cn: "卡西文", en: "Khasi" },
  { value: 35, cn: "高棉语", en: "Khmer" },
  { value: 311, cn: "Khoekhoe 语", en: "Khoekhoe language" },
  { value: 313, cn: "吉库尤文", en: "Kikuyu" },
  { value: 314, cn: "金邦杜文", en: "Kimbundu" },
  { value: 68, cn: "卢旺达文", en: "Kinyarwanda" },
  { value: 315, cn: "科米文", en: "Komi" },
  { value: 316, cn: "刚果文", en: "Kongo" },
  { value: 138, cn: "刚卡尼文", en: "Konkani" },
  { value: 520, cn: "Kordofanian 语", en: "Kordofanian languages" },
  { value: 71, cn: "韩文", en: "Korean" },
  { value: 317, cn: "科斯拉伊文", en: "Kosraean" },
  { value: 318, cn: "克佩列文", en: "Kpelle" },
  { value: 521, cn: "克里奥尔语", en: "Krio" },
  { value: 321, cn: "Kru 语", en: "Kru languages" },
  { value: 323, cn: "宽亚玛文", en: "Kuanyama" },
  { value: 324, cn: "库梅克文", en: "Kumyk" },
  { value: 72, cn: "库尔德文", en: "Kurdish" },
  { value: 322, cn: "库鲁克文", en: "Kurukh" },
  { value: 325, cn: "库特内文", en: "Kutenai" },
  { value: 69, cn: "吉尔吉斯语", en: "Kyrgyz" },
  { value: 326, cn: "拉迪诺文", en: "Ladino" },
  { value: 327, cn: "拉亨达文", en: "Lahnda" },
  { value: 328, cn: "兰巴文", en: "Lamba" },
  { value: 232, cn: "Land Dayak 语", en: "Land Dayak languages" },
  { value: 73, cn: "老挝文", en: "Lao" },
  { value: 74, cn: "拉丁文", en: "Latin" },
  { value: 75, cn: "拉脱维亚文", en: "Latvian" },
  { value: 329, cn: "莱兹依昂文", en: "Lezghian" },
  { value: 330, cn: "林堡语", en: "Limburgan" },
  { value: 76, cn: "林加拉文", en: "Lingala" },
  { value: 77, cn: "立陶宛文", en: "Lithuanian" },
  { value: 375, cn: "低地德文", en: "Low German" },
  { value: 239, cn: "下索布文", en: "Lower Sorbian" },
  { value: 332, cn: "洛兹文", en: "Lozi" },
  { value: 335, cn: "鲁巴加丹加文", en: "Luba-Katanga" },
  { value: 334, cn: "鲁巴鲁瓦文", en: "Luba-Lulua" },
  { value: 337, cn: "路易塞诺文", en: "Luiseno" },
  { value: 437, cn: "律勒欧萨米文", en: "Lule Sami" },
  { value: 338, cn: "隆达文", en: "Lunda" },
  { value: 339, cn: "卢奥文", en: "Luo" },
  { value: 340, cn: "卢晒文", en: "Lushai" },
  { value: 333, cn: "卢森堡文", en: "Luxembourgish" },
  { value: 415, cn: "阿罗马尼亚文", en: "Macedo-Romanian" },
  { value: 78, cn: "马其顿文", en: "Macedonian" },
  { value: 341, cn: "马都拉文", en: "Madurese" },
  { value: 342, cn: "马加伊文", en: "Magahi" },
  { value: 150, cn: "迈蒂利文", en: "Maithili" },
  { value: 344, cn: "望加锡文", en: "Makasar" },
  { value: 79, cn: "马尔加什文", en: "Malagasy" },
  { value: 10, cn: "马来文", en: "Malay" },
  { value: 80, cn: "马拉雅拉姆文", en: "Malayalam" },
  { value: 527, cn: "Malayo-Polynesian 语", en: "Malayo-Polynesian languages" },
  { value: 522, cn: "Maldivian 语", en: "Maldivian" },
  { value: 81, cn: "马耳他文", en: "Maltese" },
  { value: 356, cn: "满文", en: "Manchu" },
  { value: 349, cn: "曼达尔文", en: "Mandar" },
  { value: 143, cn: "普通话", en: "Mandarin" },
  { value: 345, cn: "曼丁哥文", en: "Mandingo" },
  { value: 357, cn: "曼尼普里文", en: "Manipuri" },
  { value: 358, cn: "Manobo 语", en: "Manobo languages" },
  { value: 267, cn: "马恩岛文", en: "Manx" },
  { value: 82, cn: "毛利文", en: "Maori" },
  { value: 174, cn: "马普切文", en: "Mapudungun" },
  { value: 83, cn: "马拉地文", en: "Marathi" },
  { value: 212, cn: "马里文", en: "Mari" },
  { value: 343, cn: "马绍尔文", en: "Marshallese" },
  { value: 365, cn: "马尔瓦利文", en: "Marwari" },
  { value: 347, cn: "萨伊文", en: "Masai" },
  { value: 366, cn: "Mayan 语", en: "Mayan languages" },
  { value: 350, cn: "门迪文", en: "Mende" },
  { value: 548, cn: "密克马克语", en: "Micmac" },
  { value: 153, cn: "闽南语", en: "Min Nan" },
  { value: 353, cn: "米南卡保文", en: "Minangkabau" },
  { value: 364, cn: "米兰德斯文", en: "Mirandese" },
  { value: 359, cn: "摩霍克文", en: "Mohawk" },
  { value: 348, cn: "莫克沙文", en: "Moksha" },
  { value: 531, cn: "摩尔多瓦文", en: "Moldavian" },
  { value: 331, cn: "芒戈文", en: "Mongo" },
  { value: 85, cn: "蒙古文", en: "Mongolian" },
  { value: 530, cn: "蒙特内哥罗语", en: "Montenegrin" },
  { value: 360, cn: "莫西文", en: "Mossi" },
  { value: 362, cn: "Munda 语", en: "Munda languages" },
  { value: 383, cn: "西非书面文字", en: "N'Ko" },
  { value: 539, cn: "Na-Dene 语", en: "Na-Dene languages" },
  { value: 368, cn: "Nahuatl 语", en: "Nahuatl languages" },
  { value: 86, cn: "瑙鲁文", en: "Nauru" },
  { value: 371, cn: "纳瓦霍文", en: "Navajo" },
  { value: 374, cn: "恩东加文", en: "Ndonga" },
  { value: 370, cn: "拿波里文", en: "Neapolitan" },
  { value: 87, cn: "尼泊尔文", en: "Nepali" },
  { value: 376, cn: "尼瓦尔文", en: "Newari" },
  { value: 377, cn: "尼亚斯文", en: "Nias" },
  { value: 378, cn: "Niger-Kordofanian 语", en: "Niger-Kordofanian languages" },
  { value: 446, cn: "Nilo-Saharan 语", en: "Nilo-Saharan languages" },
  { value: 379, cn: "纽埃文", en: "Niuean" },
  { value: 381, cn: "诺盖文", en: "Nogai" },
  { value: 369, cn: "North American Indian 语", en: "North American Indian" },
  { value: 506, cn: "North Caucasian 语", en: "North Caucasian languages" },
  { value: 513, cn: "North Germanic 语", en: "North Germanic languages" },
  { value: 373, cn: "北恩德贝勒文", en: "North Ndebele" },
  { value: 257, cn: "北弗里西亚文", en: "Northern Frisian" },
  { value: 435, cn: "北萨米文", en: "Northern Sami" },
  { value: 88, cn: "挪威文", en: "Norwegian" },
  { value: 142, cn: "挪威博克马尔文", en: "Norwegian Bokmål" },
  { value: 380, cn: "挪威尼诺斯克文", en: "Norwegian Nynorsk" },
  { value: 385, cn: "Nubian 语", en: "Nubian languages" },
  { value: 388, cn: "尼亚姆韦齐文", en: "Nyamwezi" },
  { value: 549, cn: "Nyaneka 语", en: "Nyaneka" },
  { value: 387, cn: "尼扬扎文", en: "Nyanja" },
  { value: 389, cn: "尼昂科勒文", en: "Nyankole" },
  { value: 550, cn: "新挪威语", en: "Nynorsk" },
  { value: 390, cn: "尼约罗文", en: "Nyoro" },
  { value: 391, cn: "恩济马文", en: "Nzima" },
  { value: 89, cn: "奥克西唐文", en: "Occitan" },
  { value: 392, cn: "奥吉布瓦文", en: "Ojibwa" },
  { value: 525, cn: "Omotic 语", en: "Omotic languages" },
  { value: 90, cn: "奥里亚文", en: "Oriya" },
  { value: 91, cn: "奥洛莫文", en: "Oromo" },
  { value: 393, cn: "奥萨格文", en: "Osage" },
  { value: 552, cn: "宽亚玛语", en: "Oshikwanyama" },
  { value: 551, cn: "恩敦加语", en: "Oshindonga" },
  { value: 394, cn: "奥塞梯语", en: "Ossetian" },
  { value: 498, cn: "其他语言", en: "Other" },
  { value: 524, cn: "Oto-Manguean 语", en: "Oto-Manguean languages" },
  { value: 396, cn: "Otomian 语", en: "Otomian languages" },
  { value: 553, cn: "奥万博语", en: "Owambo" },
  { value: 402, cn: "帕劳文", en: "Palauan" },
  { value: 400, cn: "邦板牙文", en: "Pampanga" },
  { value: 398, cn: "邦阿西楠文", en: "Pangasinan" },
  { value: 401, cn: "帕皮亚门托文", en: "Papiamento" },
  { value: 397, cn: "Papuan 语", en: "Papuan languages" },
  { value: 92, cn: "普什图语", en: "Pashto" },
  { value: 384, cn: "北索托文", en: "Pedi" },
  { value: 14, cn: "波斯文", en: "Persian" },
  { value: 144, cn: "菲律宾语", en: "Philippine languages" },
  { value: 406, cn: "波纳佩文", en: "Pohnpeian" },
  { value: 93, cn: "波兰文", en: "Polish" },
  { value: 7, cn: "葡萄牙文", en: "Portuguese" },
  {
    value: 224,
    cn: "Portuguese-Based Creoles and pidgins 语",
    en: "Portuguese-Based Creoles and pidgins",
  },
  { value: 407, cn: "Prakrit 语", en: "Prakrit languages" },
  { value: 16, cn: "旁遮普语", en: "Punjabi" },
  { value: 94, cn: "盖丘亚文", en: "Quechua" },
  { value: 410, cn: "拉贾斯坦文", en: "Rajasthani" },
  { value: 411, cn: "拉帕努伊文", en: "Rapanui" },
  { value: 412, cn: "拉罗汤加文", en: "Rarotongan" },
  { value: 413, cn: "Romance 语", en: "Romance languages" },
  { value: 96, cn: "罗马尼亚文", en: "Romanian" },
  { value: 95, cn: "罗曼什文", en: "Romansh" },
  { value: 414, cn: "吉普赛文", en: "Romany" },
  { value: 70, cn: "基隆迪文", en: "Rundi" },
  { value: 5, cn: "俄文", en: "Russian" },
  { value: 419, cn: "Salishan 语", en: "Salishan languages" },
  { value: 436, cn: "Sami 语", en: "Sami languages" },
  { value: 97, cn: "萨摩亚文", en: "Samoan" },
  { value: 535, cn: "Samoyedic 语", en: "Samoyedic languages" },
  { value: 416, cn: "散达维文", en: "Sandawe" },
  { value: 98, cn: "桑戈文", en: "Sango" },
  { value: 99, cn: "梵文", en: "Sanskrit" },
  { value: 422, cn: "桑塔利文", en: "Santali" },
  { value: 443, cn: "萨丁文", en: "Sardinian" },
  { value: 421, cn: "萨萨克文", en: "Sasak" },
  { value: 424, cn: "苏格兰文", en: "Scots" },
  { value: 48, cn: "苏格兰盖尔文", en: "Scottish Gaelic" },
  { value: 425, cn: "塞尔库普文", en: "Selkup" },
  { value: 426, cn: "Semitic 语", en: "Semitic languages" },
  { value: 100, cn: "塞尔维亚文", en: "Serbian" },
  { value: 101, cn: "塞尔维亚-克罗地亚文", en: "Serbo-Croatian" },
  { value: 445, cn: "谢列尔文", en: "Serer" },
  { value: 429, cn: "掸文", en: "Shan" },
  { value: 104, cn: "绍纳文", en: "Shona" },
  { value: 290, cn: "四川彝文", en: "Sichuan Yi" },
  { value: 423, cn: "西西里文", en: "Sicilian" },
  { value: 430, cn: "悉达摩文", en: "Sidamo" },
  { value: 428, cn: "手语", en: "Sign Languages" },
  { value: 196, cn: "司克司卡文", en: "Siksika" },
  { value: 105, cn: "信德文", en: "Sindhi" },
  { value: 106, cn: "僧伽罗文", en: "Sinhala" },
  { value: 432, cn: "Sino-Tibetan 语", en: "Sino-Tibetan languages" },
  { value: 431, cn: "Siouan 语", en: "Siouan languages" },
  { value: 439, cn: "斯科特萨米文", en: "Skolt Sami" },
  { value: 234, cn: "司雷夫文", en: "Slave" },
  { value: 433, cn: "Slavic 语", en: "Slavic languages" },
  { value: 108, cn: "斯洛伐克文", en: "Slovak" },
  { value: 109, cn: "斯洛文尼亚文", en: "Slovenian" },
  { value: 110, cn: "索马里文", en: "Somali" },
  { value: 442, cn: "Songhai 语", en: "Songhai languages" },
  { value: 440, cn: "索尼基文", en: "Soninke" },
  { value: 484, cn: "Sorbian 语", en: "Sorbian languages" },
  {
    value: 418,
    cn: "South American Indian 语",
    en: "South American Indian languages",
  },
  { value: 507, cn: "South Caucasian 语", en: "South Caucasian languages" },
  { value: 372, cn: "南恩德贝勒文", en: "South Ndebele" },
  { value: 543, cn: "South Slavic 语", en: "South Slavic languages" },
  { value: 168, cn: "南阿尔泰文", en: "Southern Altai" },
  { value: 434, cn: "南萨米文", en: "Southern Sami" },
  { value: 102, cn: "南索托文", en: "Southern Sotho" },
  { value: 3, cn: "西班牙文", en: "Spanish" },
  { value: 444, cn: "苏里南汤加文", en: "Sranan Tongo" },
  { value: 541, cn: "标准摩洛哥塔马塞特文", en: "Standard Moroccan Tamazight" },
  { value: 447, cn: "苏库马文", en: "Sukuma" },
  { value: 111, cn: "巽他文", en: "Sundanese" },
  { value: 448, cn: "苏苏文", en: "Susu" },
  { value: 112, cn: "斯瓦希里文", en: "Swahili" },
  { value: 107, cn: "斯瓦特文", en: "Swati" },
  { value: 113, cn: "瑞典文", en: "Swedish" },
  { value: 275, cn: "瑞士德文", en: "Swiss German" },
  { value: 451, cn: "叙利亚文", en: "Syriac" },
  { value: 115, cn: "塔加洛文", en: "Tagalog" },
  { value: 452, cn: "塔西提文", en: "Tahitian" },
  { value: 453, cn: "台语", en: "Tai languages" },
  { value: 116, cn: "塔吉克文", en: "Tajik" },
  { value: 462, cn: "塔马奇克文", en: "Tamashek" },
  { value: 117, cn: "泰米尔文", en: "Tamil" },
  { value: 118, cn: "塔塔尔文", en: "Tatar" },
  { value: 119, cn: "泰卢固文", en: "Telugu" },
  { value: 455, cn: "特列纳文", en: "Tereno" },
  { value: 456, cn: "特塔姆文", en: "Tetum" },
  { value: 120, cn: "泰文", en: "Thai" },
  { value: 121, cn: "藏文", en: "Tibetan" },
  { value: 536, cn: "Tibeto-Burman 语", en: "Tibeto-Burman languages" },
  { value: 457, cn: "提格雷文", en: "Tigre" },
  { value: 122, cn: "提格里尼亚文", en: "Tigrinya" },
  { value: 454, cn: "滕内文", en: "Timne" },
  { value: 458, cn: "蒂夫文", en: "Tiv" },
  { value: 461, cn: "特林吉特文", en: "Tlingit" },
  { value: 465, cn: "托克皮辛文", en: "Tok Pisin" },
  { value: 459, cn: "托克劳文", en: "Tokelau" },
  { value: 463, cn: "汤加文（尼亚萨地区）", en: "Tonga (Nyasa)" },
  { value: 464, cn: "东加语", en: "Tonga (Tonga Islands)" },
  { value: 523, cn: "Trans-New Guinea 语", en: "Trans-New Guinea languages" },
  { value: 466, cn: "蒂姆西亚文", en: "Tsimshian" },
  { value: 124, cn: "宗加文", en: "Tsonga" },
  { value: 103, cn: "塞茨瓦纳文", en: "Tswana" },
  { value: 154, cn: "图卢文", en: "Tulu" },
  { value: 467, cn: "通布卡文", en: "Tumbuka" },
  { value: 468, cn: "Tupi 语", en: "Tupi languages" },
  { value: 537, cn: "Turkic 语", en: "Turkic languages" },
  { value: 125, cn: "土耳其文", en: "Turkish" },
  { value: 126, cn: "土库曼文", en: "Turkmen" },
  { value: 470, cn: "图瓦卢文", en: "Tuvalu" },
  { value: 471, cn: "图瓦文", en: "Tuvinian" },
  { value: 472, cn: "乌德穆尔特文", en: "Udmurt" },
  { value: 474, cn: "Uighur 语", en: "Uighur" },
  { value: 128, cn: "乌克兰文", en: "Ukrainian" },
  { value: 475, cn: "翁本杜文", en: "Umbundu" },
  { value: 285, cn: "上索布文", en: "Upper Sorbian" },
  { value: 538, cn: "Uralic 语", en: "Uralic languages" },
  { value: 15, cn: "乌尔都文", en: "Urdu" },
  { value: 504, cn: "Uto-Aztecan 语", en: "Uto-Aztecan languages" },
  { value: 129, cn: "乌兹别克文", en: "Uzbek" },
  { value: 477, cn: "瓦伊文", en: "Vai" },
  { value: 478, cn: "文达文", en: "Venda" },
  { value: 130, cn: "越南文", en: "Vietnamese" },
  { value: 131, cn: "沃拉普克文", en: "Volapük" },
  { value: 479, cn: "沃提克文", en: "Votic" },
  { value: 480, cn: "Wakashan 语", en: "Wakashan languages" },
  { value: 485, cn: "瓦隆文", en: "Walloon" },
  { value: 482, cn: "瓦赖文", en: "Waray" },
  { value: 483, cn: "瓦绍文", en: "Washo" },
  { value: 132, cn: "威尔士文", en: "Welsh" },
  { value: 514, cn: "West Germanic 语", en: "West Germanic languages" },
  { value: 544, cn: "West Slavic 语", en: "West Slavic languages" },
  { value: 47, cn: "西弗里西亚文", en: "Western Frisian" },
  {
    value: 529,
    cn: "Western Malayo-Polynesian 语",
    en: "Western Malayo-Polynesian languages",
  },
  { value: 481, cn: "瓦拉莫文", en: "Wolaytta" },
  { value: 133, cn: "沃洛夫文", en: "Wolof" },
  { value: 134, cn: "科萨文", en: "Xhosa" },
  { value: 417, cn: "雅库特文", en: "Yakut" },
  { value: 487, cn: "瑶族文", en: "Yao" },
  { value: 488, cn: "雅浦文", en: "Yapese" },
  { value: 135, cn: "依地文", en: "Yiddish" },
  { value: 136, cn: "约鲁巴文", en: "Yoruba" },
  { value: 489, cn: "Yupik 语", en: "Yupik languages" },
  { value: 494, cn: "Zande 语", en: "Zande languages" },
  { value: 490, cn: "萨波蒂克文", en: "Zapotec" },
  { value: 497, cn: "扎扎文", en: "Zaza" },
  { value: 492, cn: "泽纳加文", en: "Zenaga" },
  { value: 493, cn: "壮文", en: "Zhuang" },
  { value: 137, cn: "祖鲁文", en: "Zulu" },
  { value: 495, cn: "祖尼文", en: "Zuni" },
];
export const nationalities = [
  { value: "26", code: "bt", cn: "不丹", en: "Bhutanese" },
  { value: "215", code: "tl", cn: "东帝汶", en: "East Timorese" },
  { value: "45", code: "cn", cn: "中国", en: "Chinese (China)" },
  { value: "128", code: "mo", cn: "中国澳门特别行政区", en: "Chinese (Macao)" },
  {
    value: "97",
    code: "hk",
    cn: "中国香港特别行政区",
    en: "Chinese (Hong Kong)",
  },
  { value: "211", code: "tw", cn: "中国（台湾）", en: "Chinese (Taiwan)" },
  { value: "42", code: "cf", cn: "中非共和国", en: "Central African" },
  { value: "59", code: "dk", cn: "丹麦", en: "Danish" },
  { value: "226", code: "ua", cn: "乌克兰", en: "Ukrainian" },
  { value: "232", code: "uz", cn: "乌兹别克斯坦", en: "Uzbek" },
  { value: "225", code: "ug", cn: "乌干达", en: "Ugandan" },
  { value: "231", code: "uy", cn: "乌拉圭", en: "Uruguayan" },
  { value: "43", code: "td", cn: "乍得", en: "Chadian" },
  { value: "239", code: "ye", cn: "也门", en: "Yemeni" },
  { value: "12", code: "am", cn: "亚美尼亚", en: "Armenian" },
  { value: "106", code: "il", cn: "以色列", en: "Israeli" },
  { value: "103", code: "iq", cn: "伊拉克", en: "Iraqi" },
  { value: "102", code: "ir", cn: "伊朗", en: "Iranian" },
  { value: "23", code: "bz", cn: "伯利兹", en: "Belizean" },
  { value: "40", code: "cv", cn: "佛得角", en: "Cape Verdean" },
  { value: "179", code: "ru", cn: "俄罗斯", en: "Russian" },
  { value: "34", code: "bg", cn: "保加利亚", en: "Bulgarian" },
  { value: "55", code: "hr", cn: "克罗地亚", en: "Croatian" },
  { value: "88", code: "gu", cn: "关岛", en: "Guamanian" },
  { value: "274", code: "99", cn: "其他", en: "Other" },
  { value: "79", code: "gm", cn: "冈比亚", en: "Gambian" },
  { value: "99", code: "is", cn: "冰岛", en: "Icelander" },
  { value: "91", code: "gn", cn: "几内亚", en: "Guinean" },
  { value: "92", code: "gw", cn: "几内亚比绍", en: "Guinea-Bissauan" },
  { value: "125", code: "li", cn: "列支敦士登", en: "Liechtensteiner" },
  { value: "50", code: "cg", cn: "刚果（布）", en: "Congolese (Congo)" },
  {
    value: "256",
    code: "cd",
    cn: "刚果（金）",
    en: "Congolese (Congo, The Democratic Republic Of The)",
  },
  { value: "124", code: "ly", cn: "利比亚", en: "Libyan" },
  { value: "123", code: "lr", cn: "利比里亚", en: "Liberian" },
  { value: "39", code: "ca", cn: "加拿大", en: "Canadian" },
  { value: "82", code: "gh", cn: "加纳", en: "Ghanaian" },
  { value: "78", code: "ga", cn: "加蓬", en: "Gabonese" },
  { value: "98", code: "hu", cn: "匈牙利", en: "Hungarian" },
  {
    value: "263",
    code: "mp",
    cn: "北马里亚纳群岛",
    en: "American (Northern Mariana Islands)",
  },
  {
    value: "201",
    code: "gs",
    cn: "南乔治亚岛和南桑威齐群岛",
    en: "South Georgia and the South Sandwich Islander",
  },
  { value: "252", code: "aq", cn: "南极洲", en: "Antarctica" },
  { value: "267", code: "ss", cn: "南苏丹", en: "South Sudanese" },
  { value: "200", code: "za", cn: "南非", en: "South African" },
  { value: "29", code: "bw", cn: "博茨瓦纳", en: "Motswana" },
  { value: "176", code: "qa", cn: "卡塔尔", en: "Qatari" },
  { value: "180", code: "rw", cn: "卢旺达", en: "Rwandan" },
  { value: "127", code: "lu", cn: "卢森堡", en: "Luxembourger" },
  { value: "100", code: "in", cn: "印度", en: "Indian (India)" },
  { value: "101", code: "id", cn: "印度尼西亚", en: "Indonesian" },
  { value: "89", code: "gt", cn: "危地马拉", en: "Guatemalan" },
  { value: "63", code: "ec", cn: "厄瓜多尔", en: "Ecuadorian" },
  { value: "67", code: "er", cn: "厄立特里亚", en: "Eritrean" },
  { value: "210", code: "sy", cn: "叙利亚", en: "Syrian" },
  { value: "56", code: "cu", cn: "古巴", en: "Cuban" },
  { value: "118", code: "kg", cn: "吉尔吉斯斯坦", en: "Kyrgyz" },
  { value: "60", code: "dj", cn: "吉布提", en: "Djiboutian" },
  { value: "112", code: "kz", cn: "哈萨克斯坦", en: "Kazakhstani" },
  { value: "48", code: "co", cn: "哥伦比亚", en: "Colombian" },
  { value: "53", code: "cr", cn: "哥斯达黎加", en: "Costa Rican" },
  { value: "38", code: "cm", cn: "喀麦隆", en: "Cameroonian" },
  { value: "224", code: "tv", cn: "图瓦卢", en: "Tuvaluan" },
  { value: "222", code: "tm", cn: "土库曼斯坦", en: "Turkmen" },
  { value: "221", code: "tr", cn: "土耳其", en: "Turkish" },
  { value: "184", code: "lc", cn: "圣卢西亚", en: "Saint Lucian" },
  {
    value: "183",
    code: "kn",
    cn: "圣基茨和尼维斯",
    en: "Kittian and Nevisian",
  },
  { value: "189", code: "st", cn: "圣多美和普林西比", en: "Sao Tomean" },
  {
    value: "181",
    code: "bl",
    cn: "圣巴泰勒米",
    en: "Saint Barthelemy Islander",
  },
  {
    value: "186",
    code: "vc",
    cn: "圣文森特和格林纳丁斯",
    en: "Saint Vincentian",
  },
  {
    value: "265",
    code: "pm",
    cn: "圣皮埃尔和密克隆群岛",
    en: "French (Saint Pierre And Miquelon)",
  },
  { value: "46", code: "cx", cn: "圣诞岛", en: "Christmas Island" },
  { value: "182", code: "sh", cn: "圣赫勒拿", en: "Saint Helenian" },
  { value: "188", code: "sm", cn: "圣马力诺", en: "Sammarinese" },
  { value: "93", code: "gy", cn: "圭亚那", en: "Guyanese" },
  { value: "213", code: "tz", cn: "坦桑尼亚", en: "Tanzanian" },
  { value: "64", code: "eg", cn: "埃及", en: "Egyptian" },
  { value: "69", code: "et", cn: "埃塞俄比亚", en: "Ethiopian" },
  { value: "114", code: "ki", cn: "基里巴斯", en: "Kiribatian" },
  { value: "212", code: "tj", cn: "塔吉克斯坦", en: "Tajik" },
  { value: "191", code: "sn", cn: "塞内加尔", en: "Senegalese" },
  { value: "192", code: "rs", cn: "塞尔维亚", en: "Serbian" },
  { value: "194", code: "sl", cn: "塞拉利昂", en: "Sierra Leonean" },
  { value: "57", code: "cy", cn: "塞浦路斯", en: "Cypriot" },
  { value: "193", code: "sc", cn: "塞舌尔", en: "Seychellois" },
  { value: "140", code: "mx", cn: "墨西哥", en: "Mexican" },
  { value: "216", code: "tg", cn: "多哥", en: "Togolese" },
  { value: "61", code: "dm", cn: "多米尼克", en: "Dominican (Dominica)" },
  {
    value: "258",
    code: "do",
    cn: "多米尼加共和国",
    en: "Dominican (Dominican Republic)",
  },
  { value: "253", code: "ax", cn: "奥兰群岛", en: "Finnish (Aland Islands)" },
  { value: "15", code: "at", cn: "奥地利", en: "Austrian" },
  { value: "234", code: "ve", cn: "委内瑞拉", en: "Venezuelan" },
  { value: "19", code: "bd", cn: "孟加拉国", en: "Bangladeshi" },
  { value: "7", code: "ao", cn: "安哥拉", en: "Angolan" },
  { value: "8", code: "ai", cn: "安圭拉", en: "Anguillian" },
  {
    value: "10",
    code: "ag",
    cn: "安提瓜和巴布达",
    en: "Antiguan and Barbudan",
  },
  { value: "6", code: "ad", cn: "安道尔", en: "Andorran" },
  { value: "141", code: "fm", cn: "密克罗尼西亚", en: "Micronesian" },
  { value: "157", code: "ni", cn: "尼加拉瓜", en: "Nicaraguan" },
  { value: "250", code: "ng", cn: "尼日利亚", en: "Nigerian (Nigeria)" },
  { value: "158", code: "ne", cn: "尼日尔", en: "Nigerien (Niger)" },
  { value: "152", code: "np", cn: "尼泊尔", en: "Nepalese" },
  { value: "243", code: "ps", cn: "巴勒斯坦领土", en: "Palestinian" },
  { value: "17", code: "bs", cn: "巴哈马", en: "Bahamian" },
  { value: "165", code: "pk", cn: "巴基斯坦", en: "Pakistani" },
  { value: "20", code: "bb", cn: "巴巴多斯", en: "Barbadian" },
  { value: "168", code: "pg", cn: "巴布亚新几内亚", en: "Papua New Guinean" },
  { value: "169", code: "py", cn: "巴拉圭", en: "Paraguayan" },
  { value: "167", code: "pa", cn: "巴拿马", en: "Panamanian" },
  { value: "18", code: "bh", cn: "巴林", en: "Bahraini" },
  { value: "31", code: "br", cn: "巴西", en: "Brazilian" },
  { value: "35", code: "bf", cn: "布基纳法索", en: "Burkinabe" },
  { value: "36", code: "bi", cn: "布隆迪", en: "Burundian" },
  { value: "84", code: "gr", cn: "希腊", en: "Greek" },
  { value: "166", code: "pw", cn: "帕劳", en: "Palauan" },
  { value: "52", code: "ck", cn: "库克群岛", en: "Cook Islander" },
  { value: "257", code: "cw", cn: "库拉索", en: "Dutch (Curacao)" },
  { value: "41", code: "ky", cn: "开曼群岛", en: "Caymanian" },
  { value: "81", code: "de", cn: "德国", en: "German" },
  { value: "107", code: "it", cn: "意大利", en: "Italian (Italy)" },
  { value: "198", code: "sb", cn: "所罗门群岛", en: "Solomon Islander" },
  { value: "217", code: "tk", cn: "托克劳", en: "Tokelauan" },
  { value: "120", code: "lv", cn: "拉脱维亚", en: "Latvian" },
  { value: "163", code: "no", cn: "挪威", en: "Norwegian (Norway)" },
  { value: "58", code: "cz", cn: "捷克共和国", en: "Czech" },
  { value: "142", code: "md", cn: "摩尔多瓦", en: "Moldovan" },
  { value: "147", code: "ma", cn: "摩洛哥", en: "Moroccan" },
  { value: "143", code: "mc", cn: "摩纳哥", en: "Monacan" },
  { value: "33", code: "bn", cn: "文莱", en: "Bruneian" },
  { value: "72", code: "fj", cn: "斐济", en: "Fijian" },
  { value: "207", code: "sz", cn: "斯威士兰", en: "Swazi" },
  { value: "196", code: "sk", cn: "斯洛伐克", en: "Slovak" },
  { value: "197", code: "si", cn: "斯洛文尼亚", en: "Slovenian" },
  {
    value: "266",
    code: "sj",
    cn: "斯瓦尔巴特和扬马延",
    en: "Norwegian (Svalbard And Jan Mayen)",
  },
  { value: "203", code: "lk", cn: "斯里兰卡", en: "Sri Lankan" },
  { value: "195", code: "sg", cn: "新加坡", en: "Singaporean" },
  { value: "155", code: "nc", cn: "新喀里多尼亚", en: "New Caledonian" },
  { value: "156", code: "nz", cn: "新西兰", en: "New Zealander" },
  { value: "109", code: "jp", cn: "日本", en: "Japanese" },
  { value: "44", code: "cl", cn: "智利", en: "Chilean" },
  { value: "105", code: "im", cn: "曼岛", en: "Manx" },
  { value: "115", code: "kp", cn: "朝鲜", en: "North Korean" },
  { value: "37", code: "kh", cn: "柬埔寨", en: "Cambodian" },
  { value: "90", code: "gg", cn: "根西岛", en: "Channel Islander (Guernsey)" },
  { value: "86", code: "gd", cn: "格林纳达", en: "Grenadian" },
  { value: "85", code: "gl", cn: "格陵兰", en: "Greenlandic" },
  { value: "80", code: "ge", cn: "格鲁吉亚", en: "Georgian" },
  {
    value: "271",
    code: "va",
    cn: "梵蒂冈",
    en: "Italian (Holy See (Vatican City State))",
  },
  { value: "22", code: "be", cn: "比利时", en: "Belgian" },
  { value: "137", code: "mr", cn: "毛里塔尼亚", en: "Mauritanian" },
  { value: "138", code: "mu", cn: "毛里求斯", en: "Mauritian" },
  { value: "218", code: "to", cn: "汤加", en: "Tongan" },
  { value: "190", code: "sa", cn: "沙特阿拉伯", en: "Saudi Arabian" },
  { value: "74", code: "fr", cn: "法国", en: "French (France)" },
  {
    value: "269",
    code: "tf",
    cn: "法属南部领地",
    en: "French (French Southern Territories)",
  },
  { value: "262", code: "mf", cn: "法属圣马丁", en: "Saint Martin Islander" },
  { value: "259", code: "gf", cn: "法属圭亚那", en: "French Guiana" },
  { value: "76", code: "pf", cn: "法属波利尼西亚", en: "French Polynesian" },
  { value: "71", code: "fo", cn: "法罗群岛", en: "Faroese" },
  { value: "173", code: "pl", cn: "波兰", en: "Polish" },
  { value: "175", code: "pr", cn: "波多黎各", en: "Puerto Rican" },
  {
    value: "28",
    code: "ba",
    cn: "波斯尼亚和黑塞哥维那",
    en: "Bosnian and Herzegovinian",
  },
  { value: "214", code: "th", cn: "泰国", en: "Thai" },
  { value: "261", code: "je", cn: "泽西岛", en: "Channel Islander (Jersey)" },
  { value: "241", code: "zw", cn: "津巴布韦", en: "Zimbabwean" },
  { value: "96", code: "hn", cn: "洪都拉斯", en: "Honduran" },
  { value: "94", code: "ht", cn: "海地", en: "Haitian" },
  { value: "14", code: "au", cn: "澳大利亚", en: "Australian" },
  { value: "104", code: "ie", cn: "爱尔兰", en: "Irish" },
  { value: "68", code: "ee", cn: "爱沙尼亚", en: "Estonian" },
  { value: "108", code: "jm", cn: "牙买加", en: "Jamaican" },
  {
    value: "223",
    code: "tc",
    cn: "特克斯和凯科斯群岛",
    en: "Turks and Caicos Islander",
  },
  { value: "219", code: "tt", cn: "特立尼达和多巴哥", en: "Trinidadian" },
  { value: "27", code: "bo", cn: "玻利维亚", en: "Bolivian" },
  { value: "151", code: "nr", cn: "瑙鲁", en: "Nauruan" },
  { value: "208", code: "se", cn: "瑞典", en: "Swedish (Sweden)" },
  { value: "209", code: "ch", cn: "瑞士", en: "Swiss" },
  { value: "87", code: "gp", cn: "瓜德罗普", en: "Guadeloupian" },
  {
    value: "237",
    code: "wf",
    cn: "瓦利斯和富图纳",
    en: "Wallis and Futuna Islander",
  },
  { value: "233", code: "vu", cn: "瓦努阿图", en: "Vanuatuan" },
  { value: "177", code: "re", cn: "留尼汪", en: "French (Reunion)" },
  { value: "21", code: "by", cn: "白俄罗斯", en: "Belarusian" },
  { value: "25", code: "bm", cn: "百慕大", en: "Bermudian" },
  { value: "172", code: "pn", cn: "皮特凯恩群岛", en: "Pitcairn Islander" },
  { value: "83", code: "gi", cn: "直布罗陀", en: "Gibraltarian" },
  { value: "70", code: "fk", cn: "福克兰群岛", en: "Falkland Islander" },
  { value: "117", code: "kw", cn: "科威特", en: "Kuwaiti" },
  { value: "49", code: "km", cn: "科摩罗", en: "Comoran" },
  { value: "54", code: "ci", cn: "科特迪瓦", en: "Ivorian" },
  { value: "47", code: "cc", cn: "科科斯（基林）群岛", en: "Cocos Islander" },
  { value: "249", code: "xk", cn: "科索沃", en: "Kosovan" },
  { value: "170", code: "pe", cn: "秘鲁", en: "Peruvian" },
  { value: "220", code: "tn", cn: "突尼斯", en: "Tunisian" },
  { value: "126", code: "lt", cn: "立陶宛", en: "Lithuanian" },
  { value: "199", code: "so", cn: "索马里", en: "Somali" },
  { value: "111", code: "jo", cn: "约旦", en: "Jordanian" },
  { value: "150", code: "na", cn: "纳米比亚", en: "Namibian" },
  { value: "160", code: "nu", cn: "纽埃", en: "Niuean" },
  { value: "149", code: "mm", cn: "缅甸", en: "Burmese (Myanmar)" },
  { value: "178", code: "ro", cn: "罗马尼亚", en: "Romanian" },
  { value: "229", code: "us", cn: "美国", en: "American (United States)" },
  {
    value: "270",
    code: "um",
    cn: "美国本土外小岛屿",
    en: "American (United States Minor Outlying Islands)",
  },
  {
    value: "236",
    code: "vi",
    cn: "美属维京群岛",
    en: "Virgin Islander (Virgin Islands, U.S.)",
  },
  { value: "5", code: "as", cn: "美属萨摩亚", en: "American Samoan" },
  { value: "119", code: "la", cn: "老挝", en: "Laotian" },
  { value: "113", code: "ke", cn: "肯尼亚", en: "Kenyan" },
  { value: "73", code: "fi", cn: "芬兰", en: "Finnish" },
  { value: "204", code: "sd", cn: "苏丹", en: "Sudanese" },
  { value: "205", code: "sr", cn: "苏里南", en: "Surinamese" },
  { value: "228", code: "gb", cn: "英国", en: "British" },
  {
    value: "260",
    code: "io",
    cn: "英属印度洋领地",
    en: "Indian (British Indian Ocean Territory)",
  },
  {
    value: "272",
    code: "vg",
    cn: "英属维京群岛",
    en: "Virgin Islander (Virgin Islands, British)",
  },
  { value: "153", code: "nl", cn: "荷兰", en: "Dutch (Netherlands)" },
  {
    value: "254",
    code: "bq",
    cn: "荷兰加勒比区",
    en: "Dutch (Bonaire, Sint Eustatius and Saba)",
  },
  { value: "268", code: "sx", cn: "荷属圣马丁", en: "Dutch (Sint Maarten)" },
  { value: "148", code: "mz", cn: "莫桑比克", en: "Mozambican" },
  { value: "122", code: "ls", cn: "莱索托", en: "Basotho" },
  { value: "171", code: "ph", cn: "菲律宾", en: "Filipino" },
  { value: "65", code: "sv", cn: "萨尔瓦多", en: "Salvadoran" },
  { value: "187", code: "ws", cn: "萨摩亚", en: "Samoan" },
  { value: "174", code: "pt", cn: "葡萄牙", en: "Portuguese" },
  { value: "144", code: "mn", cn: "蒙古", en: "Mongolian" },
  { value: "146", code: "ms", cn: "蒙特塞拉特", en: "Montserratian" },
  { value: "238", code: "eh", cn: "西撒哈拉", en: "Sahrawi" },
  { value: "202", code: "es", cn: "西班牙", en: "Spanish" },
  { value: "161", code: "nf", cn: "诺福克岛", en: "Norfolk Islander" },
  { value: "24", code: "bj", cn: "贝宁", en: "Beninese" },
  { value: "240", code: "zm", cn: "赞比亚", en: "Zambian" },
  { value: "66", code: "gq", cn: "赤道几内亚", en: "Equatorial Guinean" },
  {
    value: "95",
    code: "hm",
    cn: "赫德島和麥克唐納群島",
    en: "Heard and McDonald Islander",
  },
  { value: "235", code: "vn", cn: "越南", en: "Vietnamese" },
  { value: "16", code: "az", cn: "阿塞拜疆", en: "Azerbaijani" },
  { value: "1", code: "af", cn: "阿富汗", en: "Afghan" },
  { value: "4", code: "dz", cn: "阿尔及利亚", en: "Algerian" },
  { value: "3", code: "al", cn: "阿尔巴尼亚", en: "Albanian" },
  { value: "227", code: "ae", cn: "阿拉伯联合酋长国", en: "Emirati" },
  { value: "164", code: "om", cn: "阿曼", en: "Omani" },
  { value: "11", code: "ar", cn: "阿根廷", en: "Argentinean" },
  { value: "13", code: "aw", cn: "阿鲁巴", en: "Aruban" },
  { value: "116", code: "kr", cn: "韩国", en: "South Korean" },
  { value: "248", code: "mk", cn: "马其顿", en: "Macedonian" },
  { value: "132", code: "mv", cn: "马尔代夫", en: "Maldivian" },
  { value: "130", code: "mw", cn: "马拉维", en: "Malawian" },
  { value: "264", code: "mq", cn: "马提尼克", en: "French (Martinique)" },
  { value: "131", code: "my", cn: "马来西亚", en: "Malaysian" },
  { value: "273", code: "yt", cn: "马约特", en: "French (Mayotte)" },
  { value: "135", code: "mh", cn: "马绍尔群岛", en: "Marshallese" },
  { value: "134", code: "mt", cn: "马耳他", en: "Maltese" },
  { value: "129", code: "mg", cn: "马达加斯加", en: "Malagasy" },
  { value: "133", code: "ml", cn: "马里", en: "Malian" },
  { value: "255", code: "bv", cn: "鲍威特岛", en: "Bouvet Island" },
  { value: "121", code: "lb", cn: "黎巴嫩", en: "Lebanese" },
  { value: "145", code: "me", cn: "黑山共和国", en: "Montenegrin" },
];
