/**
 * Convert source SVG files in src/icons/svg into Vue components.
 *
 * Usage:
 *   npm run icons:generate
 *   npm run icons:generate -- --keep-colors
 */
import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises'
import { dirname, extname, join, relative, sep } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const svgRoot = join(root, 'src', 'icons', 'svg')
const outputRoot = join(root, 'src', 'icons', 'generated')
const indexFile = join(root, 'src', 'icons', 'index.ts')
const keepColors = process.argv.includes('--keep-colors')

const toPascalCase = (value) =>
  value
    .replace(/\\/g, '/')
    .replace(/\.svg$/i, '')
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
    .join('')

const escapeComment = (value) => value.replace(/\*\//g, '* /')

async function listSvgFiles(dir) {
  const entries = await readdir(dir, { withFileTypes: true }).catch(() => [])
  const files = await Promise.all(
    entries.map(async (entry) => {
      const path = join(dir, entry.name)

      if (entry.isDirectory()) {
        return listSvgFiles(path)
      }

      return extname(entry.name).toLowerCase() === '.svg' ? [path] : []
    })
  )

  return files.flat()
}

function normalizeSvg(source) {
  let svg = source
    .replace(/<\?xml[\s\S]*?\?>/gi, '')
    .replace(/<!doctype[\s\S]*?>/gi, '')
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/<script[\s\S]*?<\/script>/gi, '')
    .replace(/\s+on[a-z]+\s*=\s*(["']).*?\1/gi, '')
    .trim()

  if (!keepColors) {
    svg = svg
      .replace(/\sfill=(["'])(?!none\b|currentColor\b)[^"']*\1/gi, ' fill="currentColor"')
      .replace(/\sstroke=(["'])(?!none\b|currentColor\b)[^"']*\1/gi, ' stroke="currentColor"')
  }

  svg = svg.replace(/<svg\b([^>]*)>/i, (_, attrs) => {
    let nextAttrs = attrs
      .replace(/\swidth=(["']).*?\1/gi, '')
      .replace(/\sheight=(["']).*?\1/gi, '')
      .replace(/\sclass=(["']).*?\1/gi, '')
      .replace(/\saria-hidden=(["']).*?\1/gi, '')
      .replace(/\sfocusable=(["']).*?\1/gi, '')
      .trim()

    if (!/\bfill=/i.test(nextAttrs) && !keepColors) {
      nextAttrs += ' fill="currentColor"'
    }

    return `<svg ${nextAttrs} class="uni-svg-icon" aria-hidden="true" focusable="false">`
  })

  return svg
}

function createComponent(sourceFile, componentName, svg) {
  const sourcePath = relative(root, sourceFile).split(sep).join('/')

  return `<!-- Generated from ${escapeComment(sourcePath)}. Do not edit manually. -->
<template>
  ${svg}
</template>
`
}

async function main() {
  const svgFiles = await listSvgFiles(svgRoot)
  const seenNames = new Map()

  await rm(outputRoot, { force: true, recursive: true })
  await mkdir(outputRoot, { recursive: true })

  const exports = []

  for (const file of svgFiles) {
    const relativePath = relative(svgRoot, file)
    const baseName = toPascalCase(relativePath)
    const componentName = `Uni${baseName}Icon`

    if (!baseName) {
      continue
    }

    if (seenNames.has(componentName)) {
      throw new Error(
        `Duplicate icon component name "${componentName}" from "${relativePath}" and "${seenNames.get(
          componentName
        )}".`
      )
    }

    seenNames.set(componentName, relativePath)

    const outputFileName = `${componentName}.vue`
    const rawSvg = await readFile(file, 'utf8')
    const svg = normalizeSvg(rawSvg)

    if (!/^<svg\b[\s\S]*<\/svg>$/i.test(svg)) {
      throw new Error(`Invalid SVG content in "${relativePath}".`)
    }

    await writeFile(
      join(outputRoot, outputFileName),
      createComponent(file, componentName, svg),
      'utf8'
    )
    exports.push(`export { default as ${componentName} } from "./generated/${outputFileName}";`)
  }

  const indexContent =
    exports.length > 0
      ? `// This file is generated by \`npm run icons:generate\`.
// Put source SVG files in \`src/icons/svg\`.
${exports.join('\n')}
`
      : `// This file is generated by \`npm run icons:generate\`.
// Put source SVG files in \`src/icons/svg\`.
export {};
`

  await writeFile(indexFile, indexContent, 'utf8')
  console.log(`Generated ${exports.length} icon component(s).`)
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
