// This file is generated by `npm run icons:generate`.
// Put source SVG files in `src/icons/svg`.
export { default as UniBusSchool } from "./generated/UniBusSchool.vue";
export { default as UniHideMenu } from "./generated/UniHideMenu.vue";
export { default as UniLogo } from "./generated/UniLogo.vue";
export { default as UniSparkles } from "./generated/UniSparkles.vue";
export { default as UniZhEn } from "./generated/UniZhEn.vue";
