const isaData = {
    typeList: [
        { label: "学生表", value: 2, permissions: 'master_data_student_select' },
        { label: "老师表", value: 1, permissions: 'master_data_teacher_select' },
        { label: "家长表", value: 3, permissions: 'master_data_parent_select' },
        { label: "学生申请用药表", value: 4, permissions: 'service_data_stu_apply4medication_select' },
        { label: "学生餐厅信息表", value: 5, permissions: 'service_data_stu_dining_info_select' },
        { label: "学生基础医疗数据表", value: 6, permissions: 'service_data_stu_medical_basic_info_select' },
        { label: "学生医疗联系表", value: 7, permissions: 'service_data_stu_medical_contact_select' },
        { label: "学生住宿信息表", value: 8, permissions: 'service_data_stu_stay_select' },
    ],
    parentTableTitle: [
        { label: "家长爱莎ID", prop: "isaParentCode", width: "200px", fixed: 'left' },
        { label: "家长姓名", prop: "fullName", width: "200px" },
        { label: "与学生关系", prop: "relationships", width: "200px" },
        { label: "学生爱莎ID", prop: "isaStudentCode", width: "200px" },
        { label: "学号", prop: "admissonNo", width: "200px" },
        { label: "学生姓名", prop: "studentName", width: "200px" },
        { label: "学校", prop: "schoolName", width: "200px" },
        { label: "学生状态", prop: "studentStatus", width: "200px" },
        { label: "学生年级", prop: "grade", width: "200px" },
        { label: "联系电话", prop: "telephoneNumber", width: "200px" },
        { label: "是主监护人", prop: "isContactParental", width: "100px" },
        { label: "邮箱地址", prop: "emailAddress", width: "200px" },
        { label: "地址", prop: "address", width: "320px" }
    ],
    teacherTableTitle: [
        { label: "教师爱莎ID", prop: "isaTeacherCode", width: "150px", fixed: 'left' },
        { label: "姓名", prop: "fullName", width: "200px" },
        // { label: "国籍", prop: "nationalities", width: "200px" },
        { label: "性别", prop: "gender", width: "200px" },
        // { label: "年级", prop: "grade", width: "" },
        { label: "学校", prop: "schoolName", width: "" },
        { label: "任课课程", prop: "className", width: "" },
        { label: "电话号码", prop: "phoneNumber", width: "200px" },
        { label: "电子邮件", prop: "email", width: "" }
    ],
    studentTableTitle: [
        { label: "学生爱莎ID", prop: "isaStudentCode", width: "200px", fixed: 'left' },
        { label: "学号", prop: "admissonNo", width: "200px" },
        { label: "姓名", prop: "fullName", width: "200px", },
        { label: "昵称", prop: "nickname", width: "200px" },
        { label: "性别", prop: "gender", width: "100px" },
        { label: "国籍", prop: "nationality", width: "100px" },
        { label: "学校", prop: "schoolName", width: "320px" },
        { label: "年级", prop: "grade", width: "100px" },
        { label: "班级", prop: "formCode", width: "100px" },
        { label: "学生状态", prop: "studentStatus", width: "100px" },
        { label: "邮箱地址", prop: "emailAddress", width: "240px" },
        { label: "入学日期", prop: "enrolmentDate", width: "100px" },
        { label: "离开日期", prop: "leavingDate", width: "100px" },
        { label: "毕业日期", prop: "dateOfLeaving", width: "100px" }
    ],
    stuApply4MedicationTitle: [
        { label: "学生爱莎ID", prop: "isaStudentCode", width: "200px", fixed: 'left' },
        { label: "学号", prop: "admissonNo", width: "200px" },
        { label: "姓名", prop: "fullName", width: "200px", },
        { label: "昵称", prop: "nickname", width: "200px" },
        { label: "性别", prop: "gender", width: "100px" },
        { label: "学校", prop: "schoolName", width: "320px" },
        { label: "年级", prop: "grade", width: "100px" },
        { label: "班级", prop: "formCode", width: "100px" },
        { label: "定期服用药物", prop: "allergyMedication", width: "200px" },
        { label: "用药频率", prop: "frequencyOfMedication", width: "120px" },
        { label: "药物名称", prop: "medication", width: "200px" },
        { label: "申请时间", prop: "createTime", width: "200px", },
        { label: "处方", prop: "image", width: "100px" },
        { label: "签名", prop: "signature", width: "100px" },
    ],
    stuDinningInfoTitle: [
        { label: "学生爱莎ID", prop: "isaStudentCode", width: "200px", fixed: 'left' },
        { label: "学号", prop: "admissonNo", width: "200px" },
        { label: "姓名", prop: "fullName", width: "200px" },
        // { label: "昵称", prop: "nickname", width: "200px" },
        // { label: "性别", prop: "gender", width: "100px" },
        { label: "学校", prop: "schoolName", width: "320px" },
        { label: "年级", prop: "grade", width: "100px" },
        { label: "班级", prop: "formCode", width: "100px" },
        { label: "过敏源", prop: "allergySource", width: "" },
        { label: "过敏类型", prop: "allergyType", width: "100px" },
    ],
    stuMedicalBasicInfoTitle: [
        { label: "学生爱莎ID", prop: "isaStudentCode", width: "150px", fixed: 'left' },
        { label: "学号", prop: "admissonNo", width: "200px" },
        { label: "姓名", prop: "fullName", width: "200px", },
        { label: "昵称", prop: "nickname", width: "200px" },
        { label: "性别", prop: "gender", width: "100px" },
        { label: "学校", prop: "schoolName", width: "320px" },
        { label: "年级", prop: "grade", width: "100px" },
        { label: "班级", prop: "formCode", width: "100px" },
        { label: "疾病名称", prop: "disease", width: "200px" },
        { label: "定期服用药物", prop: "allergyMedication", width: "200px" },
        { label: "过敏类型", prop: "allergyType", width: "200px" },
        { label: "过敏源", prop: "allergySource", width: "200px" },
        { label: "过敏反应", prop: "allergyReaction", width: "200px" },
        { label: "具体描述", prop: "healthAllergiesDescription", width: "200px" },
    ],
    stuMedicalContactTitle: [
        { label: "学生爱莎ID", prop: "isaStudentCode", width: "150px", fixed: 'left' },
        { label: "学号", prop: "admissonNo", width: "200px" },
        { label: "姓名", prop: "fullName", width: "200px", },
        { label: "昵称", prop: "nickname", width: "" },
        { label: "性别", prop: "gender", width: "100px" },
        { label: "学校", prop: "schoolName", width: "380px" },
        { label: "年级", prop: "grade", width: "100px" },
        { label: "班级", prop: "formCode", width: "200px" },
        { label: "第一联系人关系", prop: "firstRelationship", width: "160px" },

    ],
    stuMedicalContactOtherTitle: [
        { label: "第一联系人邮箱", prop: "firstEmailAddress", width: "200px" },
        { label: "第一联系人电话", prop: "firstTelephone", width: "200px" },
        { label: "第二联系人邮箱", prop: "secondEmailAddress", width: "200px" },
        { label: "第二联系人关系", prop: "secondRelationship", width: "200px" },
        { label: "第二联系人电话", prop: "secondTelephone", width: "200px" },
    ],
    stuStayTitle: [
        { label: "学生爱莎ID", prop: "isaStudentCode", width: "150px", fixed: 'left' },
        { label: "学号", prop: "admissonNo", width: "200px" },
        { label: "姓名", prop: "fullName", width: "200px", },
        { label: "昵称", prop: "nickname", width: "200px" },
        { label: "性别", prop: "gender", width: "100px" },
        { label: "学校", prop: "schoolName", width: "320px" },
        { label: "年级", prop: "grade", width: "100px" },
        { label: "班级", prop: "formCode", width: "100px" },
        { label: "方向", prop: "divisionName", width: "200px" },
        { label: "项目名称", prop: "projectName", width: "200px" },
        { label: "楼栋名称", prop: "buildingName", width: "200px" },
        { label: "房间号", prop: "roomNum", width: "200px" },
        { label: "床位号", prop: "bedLabel", width: "200px" },
        { label: "校车信息", prop: "intentionName", width: "200px" },
        // { label: "入住时间", prop: "birthday", width: "" },
        // { label: "离开时间", prop: "birthday", width: "" },
    ],

    studentTableData: [
        { label: "头像", prop: "profilePhoto", width: "200px", fixed: 'left' },
        { label: "学生爱莎ID", prop: "isaStudentCode", width: "200px", fixed: 'left' },
        { label: "学号", prop: "admissonNo", width: "200px" },
        { label: "姓名", prop: "fullName", width: "200px", },
        { label: "昵称", prop: "nickname", width: "200px" },
        { label: "中文名", prop: "cnFullName", width: "200px" },
        { label: "性别", prop: "gender", width: "100px" },
        { label: "生日", prop: "birthday", width: "100px" },
        { label: "学校", prop: "schoolName", width: "320px" },
        { label: "年级", prop: "grade", width: "100px" },
        { label: "班级", prop: "formCode", width: "100px" },
        { label: "国籍", prop: "nationality", width: "100px" },
        { label: "语言", prop: "language", width: "100px" },
        { label: "邮箱地址", prop: "emailAddress", width: "240px" },
        { label: "方向", prop: "divisionName", width: "240px" },
        { label: "证件类型", prop: "identityType", width: "240px" },
        { label: "证件号", prop: "identityNo", width: "240px" },
        { label: "学生状态", prop: "studentStatus", width: "100px" },
        { label: "申请日期", prop: "appliedDate", width: "100px" },
        { label: "入学日期", prop: "enrolmentDate", width: "100px" },
        { label: "离开日期", prop: "leavingDate", width: "100px" },
        { label: "毕业日期", prop: "dateOfLeaving", width: "100px" }
    ],
    teacherDialogTableTitle: [
        { label: "学生爱莎ID", prop: "isaStudentCode", },
        { label: "学号", prop: "admissonNo", },
        { label: "姓名", prop: "fullName", },
        { label: "年级", prop: "grade", },
        { label: "班级", prop: "formCode", },
    ],
    teacherCouseInfo: [
        { label: "任课老师", prop: "fullName", },
        { label: "学年", prop: "yearName", },
        { label: "年级", prop: "grade", },
        { label: "学期", prop: "termName", },
        { label: "课程名", prop: "className", },
    ],
    studentStatus: [
        { label: "未入学", value: '0' },
        { label: "在校", value: '1' },
        { label: "离校", value: '2' }
    ],
    studentStatusObj: {
        0: "未入学",
        1: "在校",
        2: "离校"
    },
    genderList: [
        { label: "男-Male", value: 'Male' },
        { label: "女-Female", value: 'Female' },
    ],
    isNoList: [
        { label: "是-Yes", value: '1' },
        { label: "否-NO", value: '0' },
    ],
    relationships: [
        { label: "父亲-Father", value: 'Father' },
        { label: "母亲-Mother", value: 'Mother' },
        { label: "其他-Other", value: 'Other' },
    ],
    allergyType: [
        { label: "食物过敏", value: '1' },
        { label: "药物过敏", value: '2' },
        { label: "接触过敏", value: '3' },
    ],
    allergyTypeObj: {
        1: '食物过敏',
        2: '药物过敏',
        3: '接触过敏',
    },

}
export default isaData