export default {
  common: {
    all: '全部',
    back: '返回',
    cancel: '取消',
    close: '关闭',
    save: '保存',
    reset: '重置',
    search: '查询'
  },
  actions: {
    addCustomer: '新增客户',
    addDepartment: '新增部门',
    addConfig: '添加配置',
    addChild: '新增下级',
    batchExport: '批量导出',
    detail: '详情',
    edit: '编辑',
    follow: '跟进',
    disable: '停用',
    view: '查看'
  },
  messages: {
    exported: '已导出 {count} 条客户数据',
    createCustomer: '模板项目中这里通常打开新增客户页或弹窗',
    openCreateCustomer: '打开新增客户',
    addDepartment: '新增部门',
    addConfig: '添加配置项',
    addChild: '给 {name} 新增下级',
    edit: '编辑 {name}',
    view: '查看 {name}',
    follow: '跟进 {name}',
    disable: '停用 {name}',
    saved: '已保存 {name}',
    notFound: '未找到客户数据',
    customerFallback: '客户'
  },
  page: {
    standardTitle: '常规表格页',
    standardDescription: '搜索表单 + 远程表格 + 分页 + 批量操作，是后台列表页最常见的组合。',
    plainTitle: '无搜索表格页',
    plainDescription: '不需要筛选条件时，直接用 UniDataTable 承接接口分页和表格工具栏。',
    treeTitle: '树形表格页',
    treeDescription: '组织架构、分类目录这类层级数据，直接使用带 children 的数据源。',
    noPaginationTitle: '无分页表格页',
    noPaginationDescription: '数据量较少的配置清单、待办清单可以关闭分页，保留表格工具能力。',
    linkFormTitle: '表格跳转表单页',
    linkFormDescription: '详情和编辑都通过路由跳转承载，适合字段较多、流程较完整的业务页面。',
    dialogFormTitle: '表格打开表单弹窗',
    dialogFormDescription: '详情和编辑都在当前列表页弹窗中完成，保留筛选、分页和选中上下文。',
    detailTitle: '客户详情',
    detailDescription: '从表格页跳转进入，使用 UniForm 的查看态承载详情信息。',
    editTitle: '客户编辑',
    editDescription: '从表格页跳转进入，使用 UniForm 编辑态承载完整编辑流程。',
    selectedSummary: '已选 {selected} 项 / 共 {total} 条'
  },
  fields: {
    keyword: '关键词',
    customerNo: '客户编号',
    customerName: '客户名称',
    level: '客户等级',
    owner: '负责人',
    status: '状态',
    contractAmount: '合同金额',
    progress: '跟进进度',
    tags: '标签',
    lastFollowAt: '最近跟进',
    remark: '备注',
    departmentName: '部门名称',
    memberCount: '成员数',
    createdAt: '创建日期'
  },
  options: {
    vip: 'VIP客户',
    normal: '普通客户',
    trial: '试用客户',
    enabled: '启用',
    disabled: '停用'
  },
  placeholders: {
    customerKeyword: '客户名称 / 编号',
    autoGenerated: '系统自动生成',
    customerName: '请输入客户名称',
    level: '请选择客户等级',
    owner: '请输入负责人',
    lastFollowAt: '请选择最近跟进时间',
    remark: '请输入备注'
  },
  validation: {
    customerNameRequired: '请输入客户名称',
    levelRequired: '请选择客户等级',
    ownerRequired: '请输入负责人'
  },
  sections: {
    customerInfo: '客户信息',
    customerEdit: '编辑客户',
    detailDescription: '这里复用 UniForm 的查看态能力，适合详情页和弹窗详情。',
    editDescription: '这里复用 UniForm 的编辑态能力，适合编辑页和弹窗编辑。'
  }
}
