<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import type { Recordable, UniFormConfig, UniOption } from 'uni-ui-lib'

import { fetchCustomerDetail } from '@/api'
import { useAppI18n } from '@/composables/use-app-i18n'
import type { CustomerRecord } from '@/types/modules/uni-lib-demo'

const route = useRoute()
const router = useRouter()
const { t } = useAppI18n()

const source = ref<CustomerRecord | null>(null)
const formModel = ref<Recordable>({})
const levelOptions = computed<UniOption[]>(() => [
  { label: t('uniLibDemo.options.vip'), value: 'vip', type: 'success' },
  { label: t('uniLibDemo.options.normal'), value: 'normal', type: 'info' },
  { label: t('uniLibDemo.options.trial'), value: 'trial', type: 'warning' }
])
const editConfig = computed<UniFormConfig>(() => ({
  mode: 'edit',
  formProps: { labelWidth: '85px' },
  rowProps: { gutter: 16 },
  colProps: { span: 12 },
  rules: {
    name: [
      { required: true, message: t('uniLibDemo.validation.customerNameRequired'), trigger: 'blur' }
    ],
    level: [
      { required: true, message: t('uniLibDemo.validation.levelRequired'), trigger: 'change' }
    ],
    owner: [{ required: true, message: t('uniLibDemo.validation.ownerRequired'), trigger: 'blur' }]
  },
  schema: [
    {
      field: 'customerNo',
      label: t('uniLibDemo.fields.customerNo'),
      component: 'ElInput',
      readonly: true,
      componentProps: { placeholder: t('uniLibDemo.placeholders.autoGenerated') },
      colProps: { span: 12 }
    },
    {
      field: 'name',
      label: t('uniLibDemo.fields.customerName'),
      component: 'ElInput',
      componentProps: { placeholder: t('uniLibDemo.placeholders.customerName'), clearable: true },
      colProps: { span: 12 }
    },
    {
      field: 'level',
      label: t('uniLibDemo.fields.level'),
      component: 'ElSelect',
      options: levelOptions.value,
      componentProps: { placeholder: t('uniLibDemo.placeholders.level'), clearable: true },
      colProps: { span: 12 }
    },
    {
      field: 'owner',
      label: t('uniLibDemo.fields.owner'),
      component: 'ElInput',
      componentProps: { placeholder: t('uniLibDemo.placeholders.owner'), clearable: true },
      colProps: { span: 12 }
    },
    {
      field: 'status',
      label: t('uniLibDemo.fields.status'),
      component: 'ElSwitch',
      componentProps: { activeValue: 1, inactiveValue: 0 },
      colProps: { span: 12 }
    },
    {
      field: 'contractAmount',
      label: t('uniLibDemo.fields.contractAmount'),
      component: 'ElInputNumber',
      componentProps: { min: 0, precision: 2, controlsPosition: 'right' },
      colProps: { span: 12 }
    },
    {
      field: 'progress',
      label: t('uniLibDemo.fields.progress'),
      component: 'ElSlider',
      componentProps: { min: 0, max: 100 },
      colProps: { span: 12 }
    },
    {
      field: 'lastFollowAt',
      label: t('uniLibDemo.fields.lastFollowAt'),
      component: 'ElDatePicker',
      componentProps: {
        type: 'datetime',
        valueFormat: 'YYYY-MM-DD HH:mm:ss',
        placeholder: t('uniLibDemo.placeholders.lastFollowAt')
      },
      colProps: { span: 12 }
    },
    {
      field: 'remark',
      label: t('uniLibDemo.fields.remark'),
      component: 'ElInput',
      componentProps: {
        type: 'textarea',
        rows: 4,
        placeholder: t('uniLibDemo.placeholders.remark')
      },
      colProps: { span: 24 }
    }
  ],
  sections: [
    {
      title: t('uniLibDemo.sections.customerEdit'),
      description: t('uniLibDemo.sections.editDescription'),
      fields: [
        'customerNo',
        'name',
        'level',
        'owner',
        'status',
        'contractAmount',
        'progress',
        'lastFollowAt',
        'remark'
      ]
    }
  ]
}))

const submit = (value: Recordable) => {
  ElMessage.success(
    t('uniLibDemo.messages.saved', undefined, {
      name: String(value.name ?? t('uniLibDemo.messages.customerFallback'))
    })
  )
  router.back()
}

onMounted(async () => {
  source.value = await fetchCustomerDetail(String(route.params.id))
  formModel.value = source.value ? { ...source.value } : {}
})
</script>

<template>
  <section class="demo-page">
    <el-card shadow="never">
      <template #header>
        <div class="demo-page__header">
          <div>
            <h1>{{ t('uniLibDemo.page.editTitle') }}</h1>
            <p>{{ t('uniLibDemo.page.editDescription') }}</p>
          </div>
          <el-button @click="router.back()">{{ t('uniLibDemo.common.back') }}</el-button>
        </div>
      </template>

      <UniForm v-if="source" v-model="formModel" :config="editConfig" mode="edit" @submit="submit">
        <template #actions="{ submit: submitForm, reset }">
          <el-button type="primary" @click="submitForm">
            {{ t('uniLibDemo.common.save') }}
          </el-button>
          <el-button @click="reset">{{ t('uniLibDemo.common.reset') }}</el-button>
          <el-button @click="router.back()">{{ t('uniLibDemo.common.cancel') }}</el-button>
        </template>
      </UniForm>
      <el-empty v-else :description="t('uniLibDemo.messages.notFound')" />
    </el-card>
  </section>
</template>

<style scoped lang="scss">
.demo-page {
  display: grid;
  gap: 16px;
}

.demo-page__header {
  display: flex;
  gap: 16px;
  align-items: center;
  justify-content: space-between;

  h1 {
    margin: 0 0 8px;
    font-size: 20px;
  }

  p {
    margin: 0;
    color: var(--app-text-color-secondary);
  }
}
</style>
