export default {
  common: {
    all: 'All',
    back: 'Back',
    cancel: 'Cancel',
    close: 'Close',
    save: 'Save',
    reset: 'Reset',
    search: 'Search'
  },
  actions: {
    addCustomer: 'Add Customer',
    addDepartment: 'Add Department',
    addConfig: 'Add Config',
    addChild: 'Add Child',
    batchExport: 'Batch Export',
    detail: 'Detail',
    edit: 'Edit',
    follow: 'Follow',
    disable: 'Disable',
    view: 'View'
  },
  messages: {
    exported: 'Exported {count} customer records',
    createCustomer: 'A real project usually opens a customer create page or dialog here',
    openCreateCustomer: 'Open create customer',
    addDepartment: 'Add department',
    addConfig: 'Add config item',
    addChild: 'Add child for {name}',
    edit: 'Edit {name}',
    view: 'View {name}',
    follow: 'Follow {name}',
    disable: 'Disable {name}',
    saved: 'Saved {name}',
    notFound: 'Customer not found',
    customerFallback: 'Customer'
  },
  page: {
    standardTitle: 'Standard Table',
    standardDescription:
      'Search form, remote table, pagination, and batch actions are the most common admin list pattern.',
    plainTitle: 'Table Without Search',
    plainDescription:
      'When filters are not needed, UniDataTable can directly handle remote pagination and table tools.',
    treeTitle: 'Tree Table',
    treeDescription:
      'Organization and category data can use hierarchical rows with children directly.',
    noPaginationTitle: 'Table Without Pagination',
    noPaginationDescription:
      'Small config lists or todo lists can disable pagination while keeping table tools.',
    linkFormTitle: 'Table To Form Page',
    linkFormDescription:
      'Detail and edit forms are routed pages, which is suitable for larger forms and complete workflows.',
    dialogFormTitle: 'Table Form Dialog',
    dialogFormDescription:
      'Detail and edit forms are opened in dialogs while preserving filters, pagination, and selection context.',
    detailTitle: 'Customer Detail',
    detailDescription: 'Open from the table and use UniForm view mode to display detail fields.',
    editTitle: 'Customer Edit',
    editDescription: 'Open from the table and use UniForm edit mode to handle the full edit flow.',
    selectedSummary: 'Selected {selected} / Total {total}'
  },
  fields: {
    keyword: 'Keyword',
    customerNo: 'Customer No.',
    customerName: 'Customer Name',
    level: 'Level',
    owner: 'Owner',
    status: 'Status',
    contractAmount: 'Contract Amount',
    progress: 'Progress',
    tags: 'Tags',
    lastFollowAt: 'Last Follow-up',
    remark: 'Remark',
    departmentName: 'Department Name',
    memberCount: 'Members',
    createdAt: 'Created At'
  },
  options: {
    vip: 'VIP',
    normal: 'Normal',
    trial: 'Trial',
    enabled: 'Enabled',
    disabled: 'Disabled'
  },
  placeholders: {
    customerKeyword: 'Customer name / No.',
    autoGenerated: 'Generated by system',
    customerName: 'Please enter customer name',
    level: 'Please select customer level',
    owner: 'Please enter owner',
    lastFollowAt: 'Please select last follow-up time',
    remark: 'Please enter remark'
  },
  validation: {
    customerNameRequired: 'Please enter customer name',
    levelRequired: 'Please select customer level',
    ownerRequired: 'Please enter owner'
  },
  sections: {
    customerInfo: 'Customer Info',
    customerEdit: 'Edit Customer',
    detailDescription:
      'This reuses UniForm view mode and is suitable for detail pages and detail dialogs.',
    editDescription:
      'This reuses UniForm edit mode and is suitable for edit pages and edit dialogs.'
  }
}
