export default {
  studentTable: [
    {
      label: "ID",
      prop: "id",
      hasEn: true,
      hasColor: false,
      fixed: "left",
    },
    {
      label: "校区",
      prop: "schoolName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "学号",
      prop: "admissonNo",
      hasEn: true,
      hasColor: false,
    },

    {
      label: "中文名",
      prop: "cnFullName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "英文名",
      prop: "fullName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "年级",
      prop: "grade",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "班级",
      prop: "formCode",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "校巴",
      prop: "busStatus",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "住宿",
      prop: "dormitoryStatus",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "状态",
      prop: "studentStatus",
      hasEn: true,
      hasColor: false,
    },
  ],
  studentInfo: [
    {
      label: "ID",
      prop: "id",
      hasEn: true,
      hasColor: false,
      fixed: "left",
    },
    {
      label: "校区",
      prop: "schoolName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "学号",
      prop: "admissonNo",
      hasEn: true,
      hasColor: false,
    },

    {
      label: "中文名",
      prop: "cnFullName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "英文名",
      prop: "fullName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "昵称",
      prop: "nickname",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "出生日期",
      prop: "birthday",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "性别",
      prop: "gender",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "国籍",
      prop: "nationality",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "邮箱",
      prop: "emailAddress",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "年级",
      prop: "grade",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "班级",
      prop: "formCode",
      hasEn: true,
      hasColor: false,
    },

    {
      label: "校巴",
      prop: "busStatus",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "住宿",
      prop: "dormitoryStatus",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "住宿类型",
      prop: "boardingType",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "入学日期",
      prop: "enrolmentDate",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "离校日期",
      prop: "leavingDate",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "状态",
      prop: "studentStatus",
      hasEn: true,
      hasColor: false,
    },
  ],
  teacherTable: [
    {
      label: "ID",
      prop: "id",
      hasEn: true,
      hasColor: false,
      fixed: "left",
    },
    {
      label: "校区",
      prop: "schoolName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "工号",
      prop: "isaTeacherCode",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "姓名",
      prop: "fullName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "性别",
      prop: "gender",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "国籍",
      prop: "nationalities",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "手机号",
      prop: "phoneNumber",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "邮箱",
      prop: "email",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "职位",
      prop: "role",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "状态",
      prop: "archived",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "创建时间",
      prop: "createTime",
      hasEn: true,
      hasColor: false,
    },
  ],
  teacherInfo: [
    {
      label: "ID",
      prop: "id",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "校区",
      prop: "schoolName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "工号",
      prop: "isaTeacherCode",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "姓名",
      prop: "fullName",
      hasEn: true,
      hasColor: false,
    },

    {
      label: "手机号",
      prop: "phoneNumber",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "邮箱",
      prop: "email",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "职位",
      prop: "role",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "出生日期",
      prop: "birthday",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "性别",
      prop: "gender",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "国籍",
      prop: "nationalities",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "状态",
      prop: "archived",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "创建时间",
      prop: "createTime",
      hasEn: true,
      hasColor: false,
    },
  ],
  routeTable: [
    {
      label: "ID",
      prop: "id",
      hasEn: true,
      hasColor: false,
      width: "100px",
      fixed: "left",
    },
    {
      label: "校区",
      prop: "schoolEnNames",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "路线",
      prop: "showLineName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "路线类型",
      prop: "lineTypeName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "学期",
      prop: "showSectionName",
      hasEn: true,
      hasColor: false,
    },
    // {
    // 	label: "车牌号",
    // 	prop: "carNumber",
    // 	hasEn: true,
    // 	hasColor: false,
    // },
    // {
    // 	label: "跟车老师",
    // 	prop: "teacherName",
    // 	hasEn: true,
    // 	hasColor: false,
    // },
    // {
    // 	label: "座位数",
    // 	prop: "seatNumber",
    // 	hasEn: true,
    // 	hasColor: false,
    // },
    {
      label: "状态",
      prop: "visibleLabel",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "创建时间",
      prop: "createTime",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "更新时间",
      prop: "updateTime",
      hasEn: true,
      hasColor: false,
    },
  ],
  busTermTable: [
    {
      label: "ID",
      prop: "id",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "校区",
      prop: "schoolEnNames",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "学期",
      prop: "showTermName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "申请开始时间",
      prop: "intentStartDate",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "申请结束时间",
      prop: "intentEndDate",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "服务开始时间",
      prop: "serviceStartDate",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "服务结束时间",
      prop: "serviceEndDate",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "创建时间",
      prop: "createTime",
      hasEn: true,
      hasColor: false,
    },
  ],
  busStationTable: [
    {
      label: "ID",
      prop: "id",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "校区",
      prop: "schoolEnNames",
      hasEn: false,
      hasColor: false,
    },
    {
      label: "站点",
      prop: "showStationName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "创建时间",
      prop: "createTime",
      hasEn: true,
      hasColor: false,
    },
  ],
  bindStationTable: [
    {
      label: "站点",
      prop: "stationName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "上学上车时间",
      prop: "showGoTime",
      hasEn: false,
      hasColor: false,
    },
    {
      label: "放学下车时间",
      prop: "showBackTime",
      hasEn: false,
      hasColor: false,
    },
    {
      label: "日价格",
      prop: "price",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "周价格",
      prop: "weekPrice",
      hasEn: true,
      hasColor: false,
    },
  ],
  applyStudentTable: [
    {
      label: "ID",
      prop: "id",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "申请时间",
      prop: "createTime",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "申请状态",
      prop: "approvalStatusLabel",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "缴费状态",
      prop: "paymentStatusLabel",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "校区",
      prop: "schoolEnName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "学期",
      prop: "showSectionName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "学号",
      prop: "admissionNo",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "姓名",
      prop: "studentName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "年级",
      prop: "studentGrade",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "路线",
      prop: "showLineName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "站点",
      prop: "showStationName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "接送方式",
      prop: "pickupMethodLabel",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "创建时间",
      prop: "createTime",
      hasEn: true,
      hasColor: false,
    },
  ],
  busStudentTable: [
    {
      label: "ID",
      prop: "id",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "校区",
      prop: "id",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "学期",
      prop: "id",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "学号",
      prop: "id",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "姓名",
      prop: "id",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "路线",
      prop: "id",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "站点",
      prop: "id",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "车牌号",
      prop: "id",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "起止时间",
      prop: "id",
      hasEn: true,
      hasColor: false,
    },
  ],
  bindRouteTable: [
    {
      label: "路线",
      prop: "lineName",
      hasEn: true,
      hasColor: false,
      fixed: "left",
    },
    {
      label: "站点",
      prop: "stationName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "乘车类型",
      prop: "lineTypeName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "乘车星期",
      prop: "ridingWeekDay",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "车牌号",
      prop: "carNumber",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "开始时间",
      prop: "ridingStartDay",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "结束时间",
      prop: "ridingEndDay",
      hasEn: true,
      hasColor: false,
    },
  ],
  bindPersonTable: [
    {
      label: "关系",
      prop: "pickupRelationships",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "联系方式",
      prop: "pickupPhone",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "照片",
      prop: "pickupImageUrl",
      hasEn: true,
      hasColor: false,
    },
  ],
  orderStudentTable: [
    {
      label: "ID",
      prop: "id",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "校区",
      prop: "schoolEnName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "学期",
      prop: "showSectionName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "学号",
      prop: "admissionNo",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "姓名",
      prop: "studentName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "年级",
      prop: "studentGrade",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "路线",
      prop: "showLineName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "站点",
      prop: "showStationName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "接送方式",
      prop: "pickupMethodLabel",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "创建时间",
      prop: "createTime",
      hasEn: true,
      hasColor: false,
    },
  ],
  orderBusTable: [
    {
      label: "ID",
      prop: "id",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "申请时间",
      prop: "createTime",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "申请状态",
      prop: "approvalStatusLabel",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "缴费状态",
      prop: "paymentStatusLabel",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "应缴金额",
      prop: "amountDue",
      hasEn: true,
      hasColor: false,
    },
    // {
    // 	label: "实缴金额",
    // 	prop: "paymentAmount",
    // 	hasEn: true,
    // 	hasColor: false,
    // },
    {
      label: "校区",
      prop: "schoolEnName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "学期",
      prop: "showSectionName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "学号",
      prop: "admissionNo",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "姓名",
      prop: "studentName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "年级",
      prop: "studentGrade",
      hasEn: true,
      hasColor: false,
    },

    {
      label: "接送方式",
      prop: "pickupMethodLabel",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "创建时间",
      prop: "createTime",
      hasEn: true,
      hasColor: false,
    },
    // {
    // 	label: "拒绝理由",
    // 	prop: "denyReason",
    // 	hasEn: true,
    // 	hasColor: false,
    // },
  ],
  payInfo: [
    {
      label: "实缴金额",
      prop: "paymentAmount",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "缴费方式",
      prop: "paymentMethodLabel",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "缴费日期",
      prop: "paymentDate",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "缴费账号",
      prop: "paymentAccount",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "缴费单号",
      prop: "paymentOrderNo",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "收款账号",
      prop: "receivingAccount",
      hasEn: true,
      hasColor: false,
    },
  ],
  carTable: [
    {
      label: "ID",
      prop: "id",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "校区",
      prop: "schoolEnNames",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "车牌号",
      prop: "carNumber",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "跟车老师",
      prop: "carTeacher",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "司机姓名",
      prop: "driverName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "座位数",
      prop: "seatNumber",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "照片",
      prop: "carImageUrl",
      hasEn: true,
      hasColor: false,
      isUrl: true,
    },
    {
      label: "状态",
      prop: "statusLabel",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "创建时间",
      prop: "createTime",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "更新时间",
      prop: "updateTime",
      hasEn: true,
      hasColor: false,
    },
  ],
  carDetail: [
    {
      label: "ID",
      prop: "id",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "状态",
      prop: "statusLabel",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "校区",
      prop: "schoolEnNames",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "车牌号",
      prop: "carNumber",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "跟车老师",
      prop: "carTeacher",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "司机姓名",
      prop: "driverName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "座位数",
      prop: "seatNumber",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "创建时间",
      prop: "createTime",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "更新时间",
      prop: "updateTime",
      hasEn: true,
      hasColor: false,
    },
  ],
  bindCarTable: [
    {
      label: "校车ID",
      prop: "id",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    // {
    // 	label: "状态",
    // 	prop: "statusLabel",
    // 	hasEn: true,
    // 	hasColor: false,
    // },
    // {
    // 	label: "校区",
    // 	prop: "schoolEnNames",
    // 	hasEn: true,
    // 	hasColor: false,
    // 	width: "100px",
    // },
    {
      label: "车牌号",
      prop: "carNumber",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "跟车老师",
      prop: "carTeacher",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "司机姓名",
      prop: "driverName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "座位数",
      prop: "seatNumber",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "照片",
      prop: "carImageUrl",
      hasEn: true,
      hasColor: false,
      isUrl: true,
    },
    // {
    // 	label: "创建时间",
    // 	prop: "createTime",
    // 	hasEn: true,
    // 	hasColor: false,
    // },
    // {
    // 	label: "更新时间",
    // 	prop: "updateTime",
    // 	hasEn: true,
    // 	hasColor: false,
    // },
  ],
  busdriverTable: [
    {
      label: "ID",
      prop: "id",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "校区",
      prop: "schoolEnNames",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "司机姓名",
      prop: "name",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "工号",
      prop: "employeeNo",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "联系方式",
      prop: "contact",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "年龄",
      prop: "age",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "驾照类型",
      prop: "licenseType",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "状态",
      prop: "statusLabel",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "创建时间",
      prop: "createTime",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "更新时间",
      prop: "updateTime",
      hasEn: true,
      hasColor: false,
    },
  ],
  protocolTable: [
    {
      label: "ID",
      prop: "id",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "校区",
      prop: "schoolEnNames",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "中文名",
      prop: "cnName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "英文名",
      prop: "enName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "协议类型",
      prop: "protocolTypeName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "所属模块",
      prop: "moduleName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "是否需要签名",
      prop: "needSignLabel",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "状态",
      prop: "statusLabel",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "文档",
      prop: "documentUrl",
      hasEn: true,
      hasColor: false,
      isUrl: true,
    },
    {
      label: "创建时间",
      prop: "createTime",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "更新时间",
      prop: "updateTime",
      hasEn: true,
      hasColor: false,
    },
  ],
  followTeacherTable: [
    {
      label: "ID",
      prop: "id",
      hasEn: true,
      hasColor: false,
      fixed: "left",
    },
    {
      label: "昵称",
      prop: "nickname",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "校区",
      prop: "schoolLabel",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "部门",
      prop: "department",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "邮箱",
      prop: "email",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "手机号",
      prop: "phone",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "模块",
      prop: "modulesLabel",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "角色",
      prop: "rolesLabel",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "状态",
      prop: "statusLabel",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "最后登录时间",
      prop: "lastLoginTime",
      hasEn: true,
      hasColor: false,
    },
    // {
    // 	label: "创建时间",
    // 	prop: "createTime",
    // 	hasEn: true,
    // 	hasColor: false
    // },
  ],
  operationTable: [
    {
      label: "ID",
      prop: "id",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "状态",
      prop: "statusLabel",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "实际状态",
      prop: "arrivalStatusLabel",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "校区",
      prop: "schoolEnNames",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "学期",
      prop: "sectionName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "车牌号",
      prop: "carNumber",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "跟车老师",
      prop: "carTeacher",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "路线",
      prop: "lineName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "站点",
      prop: "stationName",
      hasEn: true,
      hasColor: false,
    },

    {
      label: "乘车日期",
      prop: "rideDate",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "到达时间",
      prop: "arrivalTime",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "创建时间",
      prop: "createTime",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "更新时间",
      prop: "updateTime",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "备注",
      prop: "remark",
      hasEn: true,
      hasColor: false,
    },
  ],
  operationInfo: [
    {
      label: "ID",
      prop: "id",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "状态",
      prop: "statusLabel",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "实际状态",
      prop: "arrivalStatusLabel",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "校区",
      prop: "schoolEnNames",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "学期",
      prop: "sectionName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "车牌号",
      prop: "carNumber",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "跟车老师",
      prop: "carTeacher",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "路线",
      prop: "lineName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "站点",
      prop: "stationName",
      hasEn: true,
      hasColor: false,
    },

    {
      label: "乘车日期",
      prop: "rideDate",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "到达时间",
      prop: "arrivalTime",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "创建时间",
      prop: "createTime",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "更新时间",
      prop: "updateTime",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "备注",
      prop: "remark",
      hasEn: true,
      hasColor: false,
      width: "100%",
    },
  ],
  exceptionTable: [
    {
      label: "ID",
      prop: "id",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "校区",
      prop: "schoolEnNames",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "学期",
      prop: "sectionName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "路线",
      prop: "lineName",
      hasEn: true,
      hasColor: false,
    },
    // {
    // 	label: "站点",
    // 	prop: "stationName",
    // 	hasEn: true,
    // 	hasColor: false,
    // },
    {
      label: "车牌号",
      prop: "carNumber",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "司机",
      prop: "driver",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "跟车老师",
      prop: "teacher",
      hasEn: true,
      hasColor: false,
    },

    {
      label: "异常类型",
      prop: "exceptionTypeLabel",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "异常日期",
      prop: "exceptionDate",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "是否调度",
      prop: "needDispatchLabel",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "调度车牌号",
      prop: "dispatchCarNumber",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "调度司机",
      prop: "dispatchDriver",
      hasEn: true,
      hasColor: false,
    },

    {
      label: "创建时间",
      prop: "createTime",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "详情",
      prop: "details",
      hasEn: true,
      hasColor: false,
    },
  ],
  exceptionInfo: [
    {
      label: "ID",
      prop: "id",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "校区",
      prop: "schoolEnNames",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "学期",
      prop: "sectionName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "路线",
      prop: "lineName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "车牌号",
      prop: "carNumber",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "司机",
      prop: "driver",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "跟车老师",
      prop: "teacher",
      hasEn: true,
      hasColor: false,
    },

    {
      label: "异常类型",
      prop: "exceptionTypeLabel",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "异常日期",
      prop: "exceptionDate",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "是否调度",
      prop: "needDispatchLabel",
      hasEn: true,
      hasColor: false,
    },
    // {
    // 	label: "调度车牌号",
    // 	prop: "dispatchCarNumber",
    // 	hasEn: true,
    // 	hasColor: false,
    // },
    // {
    // 	label: "调度司机",
    // 	prop: "dispatchDriver",
    // 	hasEn: true,
    // 	hasColor: false,
    // },

    {
      label: "创建时间",
      prop: "createTime",
      hasEn: true,
      hasColor: false,
    },
    // {
    // 	label: "详情",
    // 	prop: "details",
    // 	hasEn: true,
    // 	hasColor: false,
    // 	width: "100%",
    // },
  ],
  protocolSignTable: [
    {
      label: "ID",
      prop: "id",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "姓名",
      prop: "studentName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "学号",
      prop: "admissionNo",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "年级",
      prop: "grade",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "签名",
      prop: "signImageUrl",
      hasEn: true,
      hasColor: false,
      isUrl: true,
    },
    {
      label: "更新时间",
      prop: "updateTime",
      hasEn: true,
      hasColor: false,
    },
  ],
  voteProgramTable: [
    {
      label: "ID",
      prop: "id",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "项目名称",
      prop: "programName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "中文名",
      prop: "cnName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "英文名",
      prop: "enName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "表演者",
      prop: "performer",
      hasEn: true,
      hasColor: false,
    },
    // {
    // 	label: "中文内容",
    // 	prop: "contentCn",
    // 	hasEn: true,
    // 	hasColor: false,
    // },
    // {
    // 	label: "英文内容",
    // 	prop: "contentEn",
    // 	hasEn: true,
    // 	hasColor: false,
    // 	isUrl: true,
    // },
  ],
  wechatSchoolInfoTable: [
    {
      label: "ID",
      prop: "id",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "校区",
      prop: "schoolIdLabel",
      hasEn: true,
      hasColor: false,
      minWidth: "160px",
    },
    {
      label: "微信AppID",
      prop: "wechatAppid",
      hasEn: true,
      hasColor: false,
      minWidth: "160px",
    },
    {
      label: "推送模板",
      prop: "msgTemplateId",
      hasEn: true,
      hasColor: false,
      minWidth: "140px",
    },
    {
      label: "Token值",
      prop: "verifyToken",
      hasEn: true,
      hasColor: false,
      minWidth: "120px",
    },
    {
      label: "激活状态",
      prop: "activeLabel",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "创建时间",
      prop: "createdAt",
      hasEn: true,
      hasColor: false,
      width: "168px",
    },
    {
      label: "更新时间",
      prop: "updatedAt",
      hasEn: true,
      hasColor: false,
      width: "168px",
    },
  ],
  schoolEmailConfigTable: [
    {
      label: "ID",
      prop: "id",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "校区",
      prop: "schoolIdLabel",
      hasEn: true,
      hasColor: false,
      minWidth: "160px",
    },
    {
      label: "邮箱地址",
      prop: "email",
      hasEn: true,
      hasColor: false,
      minWidth: "200px",
    },
    {
      label: "应用模块",
      prop: "appModuleLabel",
      hasEn: true,
      hasColor: false,
      width: "120px",
    },
    {
      label: "创建时间",
      prop: "createdAt",
      hasEn: true,
      hasColor: false,
      width: "168px",
    },
    {
      label: "更新时间",
      prop: "updatedAt",
      hasEn: true,
      hasColor: false,
      width: "168px",
    },
  ],
  activityTable: [
    {
      label: "ID",
      prop: "id",
      hasEn: true,
      hasColor: false,
      width: "88px",
    },
    {
      label: "状态",
      prop: "activityStatusLabel",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "校区",
      prop: "schoolIdsLabel",
      hasEn: true,
      hasColor: false,
      minWidth: "160px",
    },
    {
      label: "中文名",
      prop: "activityCnName",
      hasEn: true,
      hasColor: false,
      minWidth: "140px",
    },
    {
      label: "英文名",
      prop: "activityEnName",
      hasEn: true,
      hasColor: false,
      minWidth: "140px",
    },
    {
      label: "开始时间",
      prop: "activityStartTime",
      hasEn: true,
      hasColor: false,
      width: "168px",
    },
    {
      label: "结束时间",
      prop: "activityEndTime",
      hasEn: true,
      hasColor: false,
      width: "168px",
    },
    {
      label: "微信提醒",
      prop: "wechatNotifyLabel",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "是否推荐",
      prop: "recommendedLabel",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "是否Banner",
      prop: "bannerLabel",
      hasEn: true,
      width: "120px",
      hasColor: false,
    },
    {
      label: "签到方式",
      prop: "checkinMethodLabel",
      hasEn: true,
      hasColor: false,
      width: "120px",
    },
    {
      label: "创建人",
      prop: "publisher",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "创建时间",
      prop: "createTime",
      hasEn: true,
      hasColor: false,
      width: "168px",
    },
    // {
    // 	label: "中文简介",
    // 	prop: "introCn",
    // 	hasEn: true,
    // 	hasColor: false,
    // },
    // {
    // 	label: "英文简介",
    // 	prop: "introEn",
    // 	hasEn: true,
    // 	hasColor: false,
    // },
    // {
    // 	label: "中文地址",
    // 	prop: "addressCn",
    // 	hasEn: true,
    // 	hasColor: false,
    // },
    // {
    // 	label: "英文地址",
    // 	prop: "addressEn",
    // 	hasEn: true,
    // 	hasColor: false,
    // },
  ],
  /** 活动详情-报名人数（购票记录） */
  activityTicketTable: [
    {
      label: "序号",
      prop: "_seq",
      hasEn: true,
      hasColor: false,
      width: "72px",
    },
    {
      label: "活动名称",
      prop: "activityName",
      hasEn: true,
      hasColor: false,
      minWidth: "160px",
    },
    {
      label: "电话",
      prop: "phone",
      hasEn: true,
      hasColor: false,
      width: "120px",
    },
    {
      label: "邮箱地址",
      prop: "email",
      hasEn: true,
      hasColor: false,
      width: "180px",
    },
    {
      label: "姓名",
      prop: "name",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "票价",
      prop: "ticketPrice",
      hasEn: true,
      hasColor: false,
      width: "88px",
    },
    {
      label: "实付金额",
      prop: "paidAmount",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "人数",
      prop: "peopleCount",
      hasEn: true,
      hasColor: false,
      width: "72px",
    },
    {
      label: "报名ID",
      prop: "id",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "是否支付",
      prop: "paidLabel",
      hasEn: true,
      hasColor: false,
      width: "88px",
    },
    {
      label: "报名时间",
      prop: "registerTimeLabel",
      hasEn: true,
      hasColor: false,
      width: "160px",
    },
  ],
  /** 活动详情-签到人数 */
  activityCheckinTable: [
    {
      label: "序号",
      prop: "_seq",
      hasEn: true,
      hasColor: false,
      width: "64px",
    },
    {
      label: "票码",
      prop: "codeStr",
      hasEn: true,
      hasColor: false,
      width: "160px",
    },
    {
      label: "电话",
      prop: "phone",
      hasEn: true,
      hasColor: false,
      width: "120px",
    },
    {
      label: "邮箱地址",
      prop: "email",
      hasEn: true,
      hasColor: false,
      width: "180px",
    },
    {
      label: "姓名",
      prop: "name",
      hasEn: true,
      hasColor: false,
      minWidth: "100px",
    },
    {
      label: "报名ID",
      prop: "ticketIdStr",
      hasEn: true,
      hasColor: false,
      minWidth: "100px",
    },
    {
      label: "是否支付",
      prop: "paidLabel",
      hasEn: true,
      hasColor: false,
      width: "88px",
    },
    {
      label: "是否参与抽奖",
      prop: "participateLotteryLabel",
      hasEn: true,
      hasColor: false,
      width: "120px",
    },
    {
      label: "是否在抽奖池内",
      prop: "lotteryValidateLabel",
      hasEn: true,
      hasColor: false,
      width: "150px",
    },
    {
      label: "是否签到",
      prop: "checkedInLabel",
      hasEn: true,
      hasColor: false,
      width: "88px",
    },
    {
      label: "签到时间",
      prop: "checkinTimeLabel",
      hasEn: true,
      hasColor: false,
      width: "160px",
    },
    {
      label: "创建时间",
      prop: "createdAtLabel",
      hasEn: true,
      hasColor: false,
      width: "160px",
    },
  ],
  /** 活动详情-投票信息（投票记录） */
  activityVoteRecordTable: [
    {
      label: "序号",
      prop: "_seq",
      hasEn: true,
      hasColor: false,
      width: "64px",
    },
    {
      label: "投票人",
      prop: "voter",
      hasEn: true,
      hasColor: false,
      width: "120px",
    },
    {
      label: "电话",
      prop: "phone",
      hasEn: true,
      hasColor: false,
      width: "128px",
    },
    {
      label: "投票项目",
      prop: "programName",
      hasEn: true,
      hasColor: false,
      minWidth: "140px",
    },
    {
      label: "投票节目",
      prop: "voteName",
      hasEn: true,
      hasColor: false,
      minWidth: "140px",
    },
    {
      label: "创建时间",
      prop: "createTimeLabel",
      hasEn: true,
      hasColor: false,
      width: "160px",
    },
  ],
  /** 活动详情-祝福语内容 */
  activityBlessingTable: [
    {
      label: "序号",
      prop: "_seq",
      hasEn: true,
      hasColor: false,
      width: "64px",
    },
    {
      label: "报名ID",
      prop: "ticketIdLabel",
      hasEn: true,
      hasColor: false,
      width: "108px",
    },
    {
      label: "内容",
      prop: "content",
      hasEn: true,
      hasColor: false,
      minWidth: "200px",
    },
    {
      label: "是否可见",
      prop: "visibleLabel",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "创建时间",
      prop: "createTimeLabel",
      hasEn: true,
      hasColor: false,
      width: "168px",
    },
  ],
  /** 活动详情-活动反馈 */
  activityFeedbackTable: [
    {
      label: "序号",
      prop: "_seq",
      hasEn: true,
      hasColor: false,
      width: "64px",
    },
    {
      label: "内容",
      prop: "content",
      hasEn: true,
      hasColor: false,
      minWidth: "180px",
    },
    {
      label: "满意度",
      prop: "satisfactionLabel",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "电话",
      prop: "phone",
      hasEn: true,
      hasColor: false,
      width: "128px",
    },
    {
      label: "是否可见",
      prop: "visibleLabel",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "创建时间",
      prop: "createTimeLabel",
      hasEn: true,
      hasColor: false,
      width: "168px",
    },
  ],
  /** 活动详情-获奖名单（抽奖类） */
  activityPrizeAwardLotteryTable: [
    {
      label: "序号",
      prop: "_seq",
      hasEn: true,
      hasColor: false,
      width: "64px",
    },
    {
      label: "项目名",
      prop: "programName",
      hasEn: true,
      hasColor: false,
      minWidth: "140px",
    },
    {
      label: "中奖票码",
      prop: "ticketCode",
      hasEn: true,
      hasColor: false,
      minWidth: "160px",
    },
    {
      label: "姓名",
      prop: "name",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "电话",
      prop: "phone",
      hasEn: true,
      hasColor: false,
      width: "120px",
    },
    {
      label: "创建时间",
      prop: "createTimeLabel",
      hasEn: true,
      hasColor: false,
      width: "160px",
    },
  ],
  /** 活动详情-获奖名单（投票类） */
  activityPrizeAwardVoteTable: [
    {
      label: "序号",
      prop: "_seq",
      hasEn: true,
      hasColor: false,
      width: "64px",
    },
    {
      label: "参赛节目",
      prop: "voteName",
      hasEn: true,
      hasColor: false,
      minWidth: "140px",
    },
    {
      label: "项目名",
      prop: "programName",
      hasEn: true,
      hasColor: false,
      minWidth: "120px",
    },
    {
      label: "总票数",
      prop: "totalVotes",
      hasEn: true,
      hasColor: false,
      width: "88px",
    },
    {
      label: "姓名",
      prop: "name",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "电话",
      prop: "phone",
      hasEn: true,
      hasColor: false,
      width: "120px",
    },
    {
      label: "创建时间",
      prop: "createTimeLabel",
      hasEn: true,
      hasColor: false,
      width: "160px",
    },
  ],
  /** 活动详情-获奖名单（比赛类） */
  activityPrizeAwardCompetitionTable: [
    {
      label: "序号",
      prop: "_seq",
      hasEn: true,
      hasColor: false,
      width: "64px",
    },
    {
      label: "项目名",
      prop: "programName",
      hasEn: true,
      hasColor: false,
      minWidth: "160px",
    },
    {
      label: "名次",
      prop: "awardRank",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "姓名",
      prop: "name",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "电话",
      prop: "phone",
      hasEn: true,
      hasColor: false,
      width: "120px",
    },
    {
      label: "创建时间",
      prop: "createTimeLabel",
      hasEn: true,
      hasColor: false,
      width: "160px",
    },
  ],
  activityProgramTable: [
    {
      label: "ID",
      prop: "id",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "活动ID",
      prop: "activityId",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "状态",
      prop: "programStatusLabel",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "中文名",
      prop: "cnName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "英文名",
      prop: "enName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "项目类型",
      prop: "programTypeLabel",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "项目顺序",
      prop: "sortOrder",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "轮次总数",
      prop: "totalRounds",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "当前轮次",
      prop: "currentRound",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "操作者",
      prop: "operator",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "操作时间",
      prop: "operateTime",
      hasEn: true,
      hasColor: false,
    },
  ],
  activityPrizeTable: [
    {
      label: "ID",
      prop: "id",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "项目名称",
      prop: "programName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "中文名",
      prop: "cnName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "英文名",
      prop: "enName",
      hasEn: true,
      hasColor: false,
    },
    // 数量 prizeCount 列暂时隐藏（奖品列表 / 详情弹窗共用 activityPrizeTable）
    // {
    //   label: "数量",
    //   prop: "prizeCount",
    //   hasEn: true,
    //   hasColor: false,
    // },
    {
      label: "金额",
      prop: "amount",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "图片",
      prop: "imageUrl",
      hasEn: true,
      hasColor: false,
      isUrl: true,
    },
    {
      label: "更新时间",
      prop: "updateTime",
      hasEn: true,
      hasColor: false,
    },
  ],
  lotteryPoolFilesTable: [
    {
      label: "ID",
      prop: "id",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "文件名",
      prop: "fileName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "更新时间",
      prop: "updateTime",
      hasEn: true,
      hasColor: false,
    },
  ],
  schoolAttendanceTable: [
    {
      label: "ID",
      prop: "id",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "校区",
      prop: "schoolName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "人员编号",
      prop: "personCode",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "人员姓名",
      prop: "personName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "所属部门",
      prop: "deptName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "卡号",
      prop: "cardNumber",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "状态",
      prop: "schoolStatus",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "入校类型",
      prop: "entryOpenType",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "入校时间",
      prop: "entryTime",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "入校通道",
      prop: "entryAscChannel",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "离校类型",
      prop: "leavingOpenType",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "离校时间",
      prop: "leavingTime",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "离校通道",
      prop: "leavingAcsChannel",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "考勤日期",
      prop: "attendanceDate",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "创建时间",
      prop: "createdAt",
      hasEn: true,
      hasColor: false,
    },
  ],
  wechatNoticeTable: [
    {
      label: "ID",
      prop: "id",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "校区",
      prop: "schoolName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "学号",
      prop: "admissionNo",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "人员姓名",
      prop: "personName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "状态",
      prop: "sendStatus",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "OpenID",
      prop: "sendOpenId",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "通知结果",
      prop: "result",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "更新时间",
      prop: "updateTime",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "创建时间",
      prop: "createTime",
      hasEn: true,
      hasColor: false,
    },
  ],
  wechatOpenidTable: [
    {
      label: "ID",
      prop: "id",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "校区",
      prop: "schoolName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "学号",
      prop: "admissionNo",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "人员姓名",
      prop: "nickname",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "状态",
      prop: "status",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "OpenID",
      prop: "encryptedOpenId",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "更新时间",
      prop: "updateTime",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "创建时间",
      prop: "createTime",
      hasEn: true,
      hasColor: false,
    },
  ],
  accessRecordTable: [
    {
      label: "ID",
      prop: "id",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "校区",
      prop: "schoolName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "所属部门",
      prop: "deptName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "人员编号",
      prop: "personCode",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "人员姓名",
      prop: "personName",
      hasEn: true,
      hasColor: false,
    },
    // {
    // 	label: "人员照片",
    // 	prop: "personImg",
    // 	hasEn: true,
    // 	hasColor: false,
    // 	isUrl: true,
    // },
    // {
    // 	label: "记录图片",
    // 	prop: "recordImageI",
    // 	hasEn: true,
    // 	hasColor: false,
    // 	isUrl: true,
    // },

    {
      label: "通道",
      prop: "acsChannelName",
      hasEn: true,
      hasColor: false,
    },

    {
      label: "考勤日期",
      prop: "attendanceDate",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "状态",
      prop: "enterOrExit",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "开门类型",
      prop: "openType",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "开门结果",
      prop: "openResult",
      hasEn: true,
      hasColor: false,
    },

    {
      label: "卡号",
      prop: "cardNumber",
      hasEn: true,
      hasColor: false,
    },
    // {
    // 	label: "卡状态",
    // 	prop: "cardStatus",
    // 	hasEn: true,
    // 	hasColor: false,
    // },
    // {
    // 	label: "卡类型",
    // 	prop: "cardType",
    // 	hasEn: true,
    // 	hasColor: false,
    // },
    {
      label: "设备名称",
      prop: "deviceName",
      hasEn: true,
      hasColor: false,
    },
    // {
    // 	label: "设备代码",
    // 	prop: "deviceCode",
    // 	hasEn: true,
    // 	hasColor: false,
    // },
    {
      label: "打卡时间",
      prop: "swingTime",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "创建时间",
      prop: "createTime",
      hasEn: true,
      hasColor: false,
    },
  ],
  studentAttendanceTable: [
    {
      label: "ID",
      prop: "id",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "校区",
      prop: "schoolName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "姓名",
      prop: "studentName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "学号",
      prop: "admissionNo",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "年级",
      prop: "grade",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "班级",
      prop: "form",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "是否住宿",
      prop: "boarding",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "是否坐校巴",
      prop: "schoolBus",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "状态",
      prop: "schoolStatus",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "考勤日期",
      prop: "attendanceDate",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "入校时间",
      prop: "entryTime",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "离校时间",
      prop: "leavingTime",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "更新时间",
      prop: "updatedAt",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "创建时间",
      prop: "createdAt",
      hasEn: true,
      hasColor: false,
    },
  ],
  questionnaireTable: [
    {
      label: "ID",
      prop: "id",
      hasEn: true,
      hasColor: false,
      width: "100px",
    },
    {
      label: "问卷名称",
      prop: "name",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "校区",
      prop: "schoolIdsLabel",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "活动",
      prop: "activityName",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "是否有效",
      prop: "statusLabel",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "是否冻结",
      prop: "frozenLabel",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "是否填写学生信息",
      prop: "needStudentInfoLabel",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "填报须知",
      prop: "instructions",
      hasEn: true,
      hasColor: false,
    },

    {
      label: "更新时间",
      prop: "updateTime",
      hasEn: true,
      hasColor: false,
    },
    {
      label: "创建时间",
      prop: "createTime",
      hasEn: true,
      hasColor: false,
    },
  ],
};
